import { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — Jannatie",
  description: "Jannatie Terms of Service. By using Jannatie, you agree to these terms.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-24 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="py-12">
            <h1 className="text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
            <p className="text-muted text-sm mb-10">Last updated: January 2025 · Jannatie Ltd, England & Wales</p>

            <div className="space-y-10 text-sm leading-relaxed">

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">1. Acceptance of terms</h2>
                <p className="text-muted">
                  By accessing or using the Jannatie service (&ldquo;Service&rdquo;), you agree to be bound
                  by these Terms of Service. If you do not agree, please do not use the Service.
                  These terms are governed by the laws of England and Wales.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">2. The Service</h2>
                <p className="text-muted mb-3">
                  Jannatie provides an AI-powered Islamic growth companion including habit tracking,
                  Islamic learning, an AI Buddy, an Islamic calendar, and progress tracking.
                </p>
                <p className="text-muted">
                  <strong className="text-foreground">AI Buddy disclaimer:</strong> Responses from the AI Buddy
                  are generated by artificial intelligence and are for general guidance only.
                  They do not constitute a fatwa, a legal ruling, or professional religious advice.
                  Always consult a qualified scholar for personal rulings.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">3. Accounts</h2>
                <ul className="space-y-2 text-muted">
                  <li>You must be at least 13 years old to create an account.</li>
                  <li>You are responsible for keeping your account credentials secure.</li>
                  <li>You may not create accounts for others without their consent.</li>
                  <li>One person per account (Family plans permit up to 5 separate accounts).</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">4. Subscriptions and payments</h2>
                <ul className="space-y-2 text-muted">
                  <li>Paid plans are billed monthly or annually as selected at checkout.</li>
                  <li>Payments are processed by Stripe. We do not store payment card data.</li>
                  <li>You may cancel at any time. Your plan continues until the end of the billing period.</li>
                  <li>We do not offer refunds for partial billing periods, except where required by law.</li>
                  <li>UK consumers have a 14-day statutory cooling-off right for digital subscriptions.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">5. Acceptable use</h2>
                <p className="text-muted mb-3">You agree not to:</p>
                <ul className="space-y-2 text-muted">
                  <li>Use the Service for any unlawful purpose</li>
                  <li>Post content that is offensive, divisive, or harmful to the Muslim community</li>
                  <li>Attempt to reverse-engineer, scrape, or automate the Service</li>
                  <li>Share your account credentials with others</li>
                  <li>Use the AI Buddy to generate content you know to be false or misleading</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">6. Intellectual property</h2>
                <p className="text-muted">
                  All content on the Service — including our learning materials, UI, and brand — is owned
                  by Jannatie Ltd. Islamic texts (Quran and hadith) are in the public domain.
                  User-generated content (your habits, notes) belongs to you.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">7. Limitation of liability</h2>
                <p className="text-muted">
                  The Service is provided &ldquo;as is&rdquo;. We are not liable for indirect, incidental,
                  or consequential damages. Our total liability in any 12-month period shall not exceed
                  the amount you paid us in that period. Nothing in these terms limits our liability
                  for death, personal injury, or fraud.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">8. Changes to terms</h2>
                <p className="text-muted">
                  We may update these terms from time to time. We will notify you by email and display
                  a banner in the app. Continued use after 30 days constitutes acceptance.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-bold text-foreground mb-3">9. Contact</h2>
                <p className="text-muted">
                  Jannatie Ltd · legal@jannatie.com · [Registered Address], England
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
