import { getQuestionsForLesson, type Question } from "./questions";

// ─── CHILD QURAN QUESTIONS (25) ─────────────────────────────────────────────
const childQuranQuestions: Question[] = [
  { question: "How many chapters (surahs) are in the Quran?", options: ["99", "112", "114", "120"], correct: 2, explanation: "The Quran has 114 chapters called surahs. Each surah has a special name and was sent by Allah to the Prophet Muhammad ﷺ.", xp: 10 },
  { question: "Which surah do we read in every unit (rak'ah) of prayer?", options: ["Surah Al-Ikhlas", "Surah Al-Fatiha", "Surah Al-Kawthar", "Surah An-Nas"], correct: 1, explanation: "We read Surah Al-Fatiha in every rak'ah of Salah. It is called 'The Opening' and is like the key to our prayers!", xp: 10 },
  { question: "What was the very first word revealed from the Quran?", options: ["Bismillah", "Iqra (Read!)", "Alhamdulillah", "Allahu Akbar"], correct: 1, explanation: "The first word was 'Iqra' which means 'Read!' The Angel Jibreel brought it to the Prophet ﷺ in the Cave of Hira.", xp: 10 },
  { question: "In which month was the Quran first revealed?", options: ["Sha'ban", "Rajab", "Ramadan", "Muharram"], correct: 2, explanation: "The Quran began to be revealed in the blessed month of Ramadan — one reason Ramadan is the most special month of the year!", xp: 10 },
  { question: "How many equal parts (juz') is the Quran divided into?", options: ["25", "28", "30", "36"], correct: 2, explanation: "The Quran is split into 30 equal juz'. Many Muslims try to read one juz' every day in Ramadan to finish the whole Quran!", xp: 10 },
  { question: "Which surah is the longest in the Quran?", options: ["Surah Al-Imran", "Surah An-Nisa", "Surah Al-Baqarah", "Surah Al-Kahf"], correct: 2, explanation: "Surah Al-Baqarah (The Cow) is the longest surah with 286 verses. The Prophet ﷺ said Shaytan runs away from a home where it is recited!", xp: 10 },
  { question: "Which is the shortest surah in the Quran?", options: ["Surah Al-Ikhlas", "Surah Al-Asr", "Surah Al-Kawthar", "Surah Al-Falaq"], correct: 2, explanation: "Surah Al-Kawthar is the shortest surah with only 3 verses. It promises the Prophet ﷺ a beautiful river in Paradise.", xp: 10 },
  { question: "Which surah is known as the 'heart of the Quran'?", options: ["Surah Al-Fatiha", "Surah Al-Baqarah", "Surah Ya-Sin", "Surah Al-Ikhlas"], correct: 2, explanation: "Surah Ya-Sin is called the heart of the Quran! Muslims often recite it on Fridays and for those who are sick.", xp: 10 },
  { question: "What is the name of the special rules for reading the Quran beautifully?", options: ["Seerah", "Tajweed", "Fiqh", "Hadith"], correct: 1, explanation: "Tajweed is the set of rules that help us pronounce the Quran correctly and beautifully. The Prophet ﷺ always recited in a clear, measured way.", xp: 10 },
  { question: "Which short surah is said to equal one-third of the Quran in reward?", options: ["Surah Al-Fatiha", "Surah Al-Kahf", "Surah Al-Ikhlas", "Surah Al-Falaq"], correct: 2, explanation: "Surah Al-Ikhlas is said to equal one-third of the Quran in reward because it perfectly describes Allah's Oneness. It is only 4 short verses long!", xp: 10 },
  { question: "What does the word 'Quran' actually mean?", options: ["The Book of God", "That which is recited/read", "The Words of Peace", "The Final Revelation"], correct: 1, explanation: "The word 'Quran' comes from the Arabic word meaning 'to read' or 'to recite'. The Quran is meant to be read aloud with a beautiful voice!", xp: 10 },
  { question: "Where was the first verse of the Quran revealed?", options: ["The Ka'bah in Makkah", "Madinah", "Cave of Hira", "Jerusalem"], correct: 2, explanation: "The first verses were revealed to the Prophet ﷺ in the Cave of Hira on Mount Nur, near Makkah. He used to go there to think and worship Allah.", xp: 10 },
  { question: "What do we say before we start reading the Quran?", options: ["Alhamdulillah", "Bismillah", "A'udhu billahi min ash-Shaytan ir-rajeem", "Subhanallah"], correct: 2, explanation: "Before reading the Quran we say 'A'udhu billahi min ash-Shaytan ir-rajeem' — asking Allah to protect us from Shaytan so we can focus fully.", xp: 10 },
  { question: "Which angel brought the Quran from Allah to the Prophet ﷺ?", options: ["Mikail", "Jibreel (Gabriel)", "Israfeel", "Munkar"], correct: 1, explanation: "It was the Angel Jibreel (Gabriel) who brought the Quran from Allah to the Prophet ﷺ over 23 years. Jibreel is called the 'trustworthy spirit'.", xp: 10 },
  { question: "How many years did it take for the whole Quran to be revealed?", options: ["10 years", "13 years", "23 years", "30 years"], correct: 2, explanation: "The Quran was revealed over 23 years — 13 years in Makkah and 10 years in Madinah. Each part came at exactly the right time.", xp: 10 },
  { question: "What are the two 'Surahs of Protection' we often recite together?", options: ["Al-Fatiha and Al-Ikhlas", "Al-Falaq and An-Nas", "Al-Kawthar and Al-Asr", "Al-Fil and Quraysh"], correct: 1, explanation: "Al-Falaq and An-Nas are called the two surahs of protection! The Prophet ﷺ recited them every morning, every evening, and before sleeping.", xp: 10 },
  { question: "What is the first surah in the Quran called?", options: ["Al-Baqarah", "Al-Fatiha", "Ya-Sin", "Al-Ikhlas"], correct: 1, explanation: "The first surah is Al-Fatiha (The Opening). It is also called 'Umm al-Kitab' which means 'Mother of the Book'!", xp: 10 },
  { question: "A person who has memorised the whole Quran is called a...?", options: ["Hafidh", "Sheikh", "Imam", "Mufti"], correct: 0, explanation: "Someone who has memorised the entire Quran is called a Hafidh (man) or Hafidhah (woman). This is one of the greatest achievements in Islam!", xp: 10 },
  { question: "The last section of the Quran, full of short surahs, is called...?", options: ["Juz Al-Baqarah", "Juz Amma", "Juz Tabarak", "Juz Qad Sami'a"], correct: 1, explanation: "The last section is called 'Juz Amma'. It contains many short surahs we learn first, like Al-Ikhlas, Al-Falaq, An-Nas, and Al-Kawthar!", xp: 10 },
  { question: "How should we treat our physical Quran (mushaf) to show respect?", options: ["Place it anywhere", "Put it on the floor", "Keep it in a clean, high place and handle it gently", "Lend it without care"], correct: 2, explanation: "We should treat the Quran with great respect — keep it clean, handle it gently, place it up high, and be in a state of cleanliness before touching it.", xp: 10 },
  { question: "Which surah tells us that time is passing and only good deeds save us?", options: ["Surah Al-Asr", "Surah Al-Fil", "Surah Al-Humazah", "Surah At-Tin"], correct: 0, explanation: "Surah Al-Asr (Time) tells us: 'By time, mankind is indeed in loss!' — reminding us to use our time wisely with good deeds and being kind.", xp: 10 },
  { question: "The Quran was collected into one official book by which Caliph?", options: ["Umar (RA)", "Abu Bakr (RA)", "Uthman (RA)", "Ali (RA)"], correct: 2, explanation: "Caliph Uthman (RA) collected all copies of the Quran into one official version. He is called 'Jami' al-Quran' — the Compiler of the Quran.", xp: 10 },
  { question: "What is Ayat al-Kursi and why is it so important?", options: ["A du'a for rain", "The greatest verse in the Quran, found in Surah Al-Baqarah", "A surah about angels", "The last verse of the Quran"], correct: 1, explanation: "Ayat al-Kursi (2:255) is the greatest verse in the Quran! The Prophet ﷺ said whoever reads it after every prayer will enter Paradise.", xp: 10 },
  { question: "What is it called when we think deeply about the meaning of Quran verses?", options: ["Tafseer", "Tajweed", "Tadabbur", "Taleem"], correct: 2, explanation: "Tadabbur means 'deep reflection' on the Quran. Allah says: 'Do they not reflect upon the Quran?' — He wants us to think, not just read!", xp: 10 },
  { question: "The Prophet ﷺ said a believer who reads the Quran is like which fruit?", options: ["A grape — sweet and juicy", "An orange (citron) — pleasant smell and sweet taste", "A date — sweet all through", "A watermelon — refreshing in summer"], correct: 1, explanation: "The Prophet ﷺ said: 'A believer who recites the Quran is like an orange (utrujjah) — pleasant smell and sweet taste.' Reading the Quran beautifies you inside and outside!", xp: 10 },
];

// ─── CHILD DUAS QUESTIONS (25) ───────────────────────────────────────────────
const childDuasQuestions: Question[] = [
  { question: "What is a 'Du'a'?", options: ["A type of Islamic book", "A prayer where we talk directly to Allah", "A Muslim greeting", "A type of Islamic rule"], correct: 1, explanation: "A du'a is when we talk directly to Allah and ask for His help, forgiveness, or blessings. The Prophet ﷺ called du'a 'the essence of worship'!", xp: 10 },
  { question: "What do we say before we start eating?", options: ["Alhamdulillah", "Bismillah", "Subhanallah", "Allahu Akbar"], correct: 1, explanation: "We say 'Bismillah' (In the name of Allah) before eating. This is a Sunnah of the Prophet ﷺ. If we forget, we say 'Bismillahi fi awwalihi wa akhirih'!", xp: 10 },
  { question: "What do we say after we finish eating?", options: ["Bismillah", "Allahu Akbar", "Alhamdulillah", "SubhanAllah"], correct: 2, explanation: "After eating we say 'Alhamdulillah' (All praise is for Allah). We always thank Allah for giving us food!", xp: 10 },
  { question: "What du'a do we say before going to sleep?", options: ["Astaghfirullah", "Allahumma bismika amutu wa ahya (O Allah, in Your name I die and live)", "A'udhu billah", "Subhanallah 33 times"], correct: 1, explanation: "Before sleeping we say 'Allahumma bismika amutu wa ahya' — putting our night in Allah's hands. We also recite Al-Ikhlas, Al-Falaq, and An-Nas!", xp: 10 },
  { question: "What do we say when we wake up in the morning?", options: ["Alhamdulillah only", "Alhamdulillahilladhi ahyaana ba'da ma amaatana (Praise Allah who brought us back to life)", "Bismillah", "Subhanallah"], correct: 1, explanation: "When we wake up we thank Allah for giving us another day! We say 'Alhamdulillahilladhi ahyaana ba'da ma amaatana wa ilayhin-nushoor'.", xp: 10 },
  { question: "What do we say when entering the bathroom?", options: ["Nothing is needed", "Bismillah", "Allahumma innee a'udhu bika minal-khubuthi wal-khaba'ith (asking Allah to protect us from evil)", "Subhanallah"], correct: 2, explanation: "Before entering the bathroom we ask Allah to protect us by saying 'Allahumma innee a'udhu bika minal-khubuthi wal-khaba'ith'. We also enter with our left foot!", xp: 10 },
  { question: "What do we say when we leave the house?", options: ["Allahu Akbar", "Bismillah, tawakkaltu 'alAllah (I trust in Allah)", "Assalamu Alaykum", "Subhanallah wa bihamdihi"], correct: 1, explanation: "When leaving home we say 'Bismillah, tawakkaltu 'alAllah' — putting our trust in Allah before stepping out into the world!", xp: 10 },
  { question: "What do we say when we enter the mosque (masjid)?", options: ["Bismillah only", "Allahumma iftah lee abwaba rahmatik (O Allah, open for me Your mercy)", "Allahu Akbar", "SubhanAllah"], correct: 1, explanation: "When entering the mosque we say 'Allahumma iftah lee abwaba rahmatik' — asking Allah to open the doors of His mercy for us. We enter with our right foot!", xp: 10 },
  { question: "What is 'Dhikr'?", options: ["A type of Islamic school", "Remembering and mentioning Allah", "An Islamic celebration", "A prayer mat"], correct: 1, explanation: "Dhikr means remembering Allah by saying Subhanallah, Alhamdulillah, Allahu Akbar, and La ilaha illallah. Allah says in the Quran: 'Remember Me, and I will remember you!'", xp: 10 },
  { question: "How many times do we say Subhanallah, Alhamdulillah, and Allahu Akbar after each prayer?", options: ["10 times each", "25 times each", "33 times each", "100 times each"], correct: 2, explanation: "After each prayer we say Subhanallah 33 times, Alhamdulillah 33 times, Allahu Akbar 33 times (total 99), then one more special phrase to make 100!", xp: 10 },
  { question: "What do Muslims say when they hear news of a death or something very sad?", options: ["Alhamdulillah", "Inna lillahi wa inna ilayhi raji'oon (We belong to Allah and to Him we return)", "SubhanAllah", "Allahu Akbar"], correct: 1, explanation: "We say 'Inna lillahi wa inna ilayhi raji'oon' (Quran 2:156). This beautiful phrase reminds us that everything belongs to Allah — and that His plan is always right.", xp: 10 },
  { question: "What do we say when we sneeze?", options: ["Bismillah", "Alhamdulillah, then yarhamukallah", "Subhanallah", "Allahu Akbar"], correct: 1, explanation: "When we sneeze, we say 'Alhamdulillah'. The people nearby say 'Yarhamukallah' (May Allah have mercy on you). We reply 'Yahdikumullah' (May Allah guide you)!", xp: 10 },
  { question: "What is 'Istighfar' and how do we do it?", options: ["Praising Allah by saying Subhanallah", "Asking Allah for forgiveness by saying Astaghfirullah", "Thanking Allah by saying Alhamdulillah", "Asking for help by saying HasbunAllah"], correct: 1, explanation: "Istighfar means asking Allah to forgive us — we say 'Astaghfirullah'. The Prophet ﷺ said this at least 70 to 100 times every single day!", xp: 10 },
  { question: "What du'a do we say when we feel worried or afraid?", options: ["Alhamdulillah", "HasbunAllahu wa ni'mal wakeel (Allah is enough for us, what a great Protector!)", "Bismillah", "Allahu Akbar"], correct: 1, explanation: "When we feel worried we say 'HasbunAllahu wa ni'mal wakeel'. Prophet Ibrahim (AS) said these words when he was thrown into the fire — and Allah saved him!", xp: 10 },
  { question: "What do we say at the start of wudu (washing before prayer)?", options: ["Subhanallah", "Bismillah", "Allahu Akbar", "Alhamdulillah"], correct: 1, explanation: "We start wudu by saying 'Bismillah'. It's a simple but important step — reminding ourselves we are getting ready to worship Allah!", xp: 10 },
  { question: "What special du'a do we say when we see the new crescent moon?", options: ["Bismillah", "Allahu Akbar, Allahumma ahillahu alayna bil-yumni wal-iman (with blessings and faith)", "Subhanallah", "Allahu Akbar only"], correct: 1, explanation: "When we spot the new moon we say a special du'a asking Allah to bring us blessings and faith through this new month. It is a beautiful Sunnah!", xp: 10 },
  { question: "What is 'Sayyidul Istighfar'?", options: ["The longest surah in the Quran", "The master (best) du'a for seeking forgiveness", "A special Friday prayer", "A chapter about the prophets"], correct: 1, explanation: "Sayyidul Istighfar is the 'Master of Forgiveness' du'a — a beautiful, complete way to say sorry to Allah. The Prophet ﷺ called it the best forgiveness du'a!", xp: 10 },
  { question: "What should we say before starting any important task?", options: ["SubhanAllah", "Bismillah (In the name of Allah)", "Alhamdulillah", "La hawla wa la quwwata illa billah"], correct: 1, explanation: "We say 'Bismillah' before anything important — eating, studying, reading Quran, going on a journey. It invites Allah's blessing into everything we do!", xp: 10 },
  { question: "What do we say when something really great happens?", options: ["Bismillah", "Alhamdulillah (All praise to Allah!)", "Subhanallah", "Allahu Akbar"], correct: 1, explanation: "When something wonderful happens we say 'Alhamdulillah!' — thanking Allah for His blessing. Even if something is difficult, a believer still says Alhamdulillah!", xp: 10 },
  { question: "What is Ayat al-Kursi and when should we read it?", options: ["A du'a for rain — read in drought", "Quran 2:255 — read after prayers and before sleeping for protection", "A du'a for travel", "A surah about angels"], correct: 1, explanation: "Ayat al-Kursi (2:255) is the greatest verse in the Quran! Reading it after every prayer and before sleeping gives us amazing protection from Allah.", xp: 10 },
  { question: "What was the du'a of Prophet Yunus (AS) while inside the whale?", options: ["Rabbana atina fid-dunya hasana...", "La ilaha illa anta subhanaka inni kuntu minaz-zaalimeen (There is no god but You, I was wrong)", "HasbunAllahu wa ni'mal wakeel", "Rabbi la tadharni fardan"], correct: 1, explanation: "While inside the whale, Yunus (AS) made this beautiful du'a admitting his mistake and calling on Allah alone. Allah answered and saved him!", xp: 10 },
  { question: "How should we feel inside when we make du'a to Allah?", options: ["Worried He won't answer", "Hopeful and certain Allah will answer in the best way", "Unsure if He hears", "Rushed and quick to finish"], correct: 1, explanation: "When we make du'a we should feel certain (yaqeen) that Allah hears us and will answer — either by giving what we asked, something better, or saving us from harm!", xp: 10 },
  { question: "What is a special hour on Friday when du'as are accepted?", options: ["At Fajr time", "Between Asr and Maghrib prayer", "At midnight", "Before Jumu'ah only"], correct: 1, explanation: "The Prophet ﷺ told us there is a special hour on Friday between Asr and Maghrib when du'as are accepted. Many Muslims use this precious time to ask Allah for their needs!", xp: 10 },
  { question: "If Allah doesn't give us exactly what we asked for, what does that mean?", options: ["Our du'a was rejected", "Allah forgot our du'a", "Allah is giving us something better or protecting us from something harmful", "We made a mistake in our du'a"], correct: 2, explanation: "Allah always hears our du'a! He might give us something better, save the reward for the Hereafter, or protect us from something bad. Trust Allah's plan — it is always the best!", xp: 10 },
  { question: "What is 'Tawakkul'?", options: ["Reading lots of Quran", "Trusting completely in Allah after doing your best", "Praying extra night prayers", "Giving lots of charity"], correct: 1, explanation: "Tawakkul means trusting Allah completely. We do our best, then say 'Tawakkaltu 'alAllah' — I trust in Allah! Like the Prophet ﷺ said: 'Tie your camel, then put your trust in Allah.'", xp: 10 },
];

// ─── CHILD MANNERS QUESTIONS (25) ───────────────────────────────────────────
const childMannersQuestions: Question[] = [
  { question: "What did the Prophet ﷺ say he was sent to teach us?", options: ["Perfect Islamic law", "Perfect good character and behaviour", "The best Arabic", "The most prayers"], correct: 1, explanation: "The Prophet ﷺ said: 'I was sent to perfect good character.' Being kind, honest, and well-mannered is one of the most important things in Islam!", xp: 10 },
  { question: "How do we greet other Muslims?", options: ["Hi! or Hello!", "Assalamu Alaykum (Peace be upon you)", "Good morning", "Bismillah"], correct: 1, explanation: "We greet Muslims with 'Assalamu Alaykum'. The full greeting is 'Assalamu Alaykum wa Rahmatullahi wa Barakatuh'. The Prophet ﷺ said spreading salaam earns great rewards!", xp: 10 },
  { question: "Which hand should we eat with according to the Sunnah?", options: ["Left hand", "Either hand", "Right hand", "With a spoon only"], correct: 2, explanation: "The Prophet ﷺ taught us to eat with our right hand. He said Shaytan eats with his left hand — so eating with the right is a Sunnah that protects us!", xp: 10 },
  { question: "How does Islam teach us to treat our parents?", options: ["Obey them only when we agree", "Respect, obey, and be kind to them — even saying 'uff' is not allowed!", "Treat them like friends", "Only respect them when they are kind to us"], correct: 1, explanation: "Allah says in the Quran (17:23): 'Be kind to your parents.' We are not even allowed to say 'uff' (a sound of irritation) to them — that is how much Islam respects parents!", xp: 10 },
  { question: "What is the Islamic teaching about always telling the truth?", options: ["Lie if it avoids trouble", "Always speak the truth, even when it is difficult", "White lies are fine in Islam", "Only be honest at the mosque"], correct: 1, explanation: "The Prophet ﷺ said: 'Truthfulness leads to goodness and goodness leads to Paradise.' Honesty is one of the most important qualities of a Muslim. The Prophet ﷺ was called 'Al-Amin' (the Trustworthy)!", xp: 10 },
  { question: "What should a Muslim do when they feel very angry?", options: ["Say exactly what they feel", "Walk away, make wudu, and remember Allah", "Argue back immediately", "Cry loudly"], correct: 1, explanation: "The Prophet ﷺ said 'Do not be angry' three times! When angry: change position (sit if standing), make wudu, and seek refuge in Allah from Shaytan.", xp: 10 },
  { question: "When someone says 'Assalamu Alaykum' to us, what do we reply?", options: ["Hello back!", "Wa Alaykum Assalam (And peace be upon you too)", "Bismillah", "Allahu Akbar"], correct: 1, explanation: "We reply with 'Wa Alaykum Assalam' or even better, 'Wa Alaykum Assalam wa Rahmatullahi wa Barakatuh'. This spreads peace and love between Muslims!", xp: 10 },
  { question: "How should we treat animals in Islam?", options: ["However we like", "With kindness and care — hurting animals is a serious sin", "Only if they are useful to us", "Only feed them, nothing more"], correct: 1, explanation: "The Prophet ﷺ said a woman entered Hellfire for locking up a cat without feeding it! But a sinful man entered Paradise for giving water to a thirsty dog. Be kind to all animals!", xp: 10 },
  { question: "The Prophet ﷺ said 'Cleanliness is half of...?'", options: ["The prayer", "Faith (Iman)", "The Quran", "Being a good Muslim"], correct: 1, explanation: "The Prophet ﷺ said 'Cleanliness is half of faith!' Keeping our body, clothes, and home clean is an act of worship in Islam. We must be clean before Salah too.", xp: 10 },
  { question: "How many houses in each direction counts as your 'neighbour' in Islam?", options: ["3 houses", "7 houses", "40 houses", "10 houses"], correct: 2, explanation: "The Prophet ﷺ said Jibreel kept advising him about neighbours until he thought they would inherit from each other! Scholars say this covers up to 40 houses in each direction.", xp: 10 },
  { question: "The Prophet ﷺ said that smiling at your brother is a...?", options: ["Waste of time", "Charity (sadaqah)!", "Only nice, not a reward", "Something only adults do"], correct: 1, explanation: "The Prophet ﷺ said: 'Your smile for your brother is a charity (sadaqah)!' Even a simple smile is an act of worship. The Prophet ﷺ was always known for his warm, beautiful smile.", xp: 10 },
  { question: "What should we do before entering someone's home?", options: ["Walk in if the door is open", "Knock, say Assalamu Alaykum, and wait for permission", "Shout their name from outside", "Ring the bell only once"], correct: 1, explanation: "Allah tells us in the Quran (24:27): 'Do not enter houses other than your own until you ask permission and greet those inside.' We must ask up to three times — if no answer, we leave!", xp: 10 },
  { question: "What is 'Sabr' and why is it important?", options: ["Being happy all the time", "Patience — keeping calm and trusting Allah in hard times", "Running away from problems", "Asking others for help"], correct: 1, explanation: "Sabr means patience. Allah says: 'Indeed, Allah is with the patient.' (2:153). When things are tough, the Muslim stays calm, makes du'a, and trusts that Allah's plan is best.", xp: 10 },
  { question: "What does Islam say about wasting food?", options: ["It is fine if you have plenty", "Wasting is a sin — only take what you will eat and avoid israf", "Only expensive food should not be wasted", "Children don't need to think about this"], correct: 1, explanation: "Islam teaches us to avoid 'israf' (waste and excess). The Prophet ﷺ would clean his plate after eating and never wasted food. Be grateful and take only what you'll eat!", xp: 10 },
  { question: "What is 'Sila al-Rahm' (keeping family ties) and why does it matter?", options: ["Giving charity to strangers", "Staying close to family and relatives", "Attending Islamic school", "Visiting the mosque daily"], correct: 1, explanation: "Sila al-Rahm means keeping family ties. The Prophet ﷺ said cutting family ties keeps someone from entering Paradise! Visit relatives, call them, and be kind to them.", xp: 10 },
  { question: "The Prophet ﷺ said the truly strong person is not someone who wins fights — what makes someone truly strong?", options: ["Having big muscles", "Controlling yourself when you are angry", "Being the fastest runner", "Winning every argument"], correct: 1, explanation: "The Prophet ﷺ said: 'The strong person controls themselves when angry.' True strength in Islam is about controlling your feelings — not about muscles or winning fights!", xp: 10 },
  { question: "What should we say when we see something beautiful, like a new baby or lovely view?", options: ["Wow!", "Masha'Allah (What Allah has willed)", "SubhanAllah only", "Allahu Akbar only"], correct: 1, explanation: "We say 'Masha'Allah' when we see something beautiful. This also protects against the evil eye. It's our way of acknowledging that all beauty comes from Allah!", xp: 10 },
  { question: "How did the Prophet ﷺ react when people in Ta'if were rude and hurt him?", options: ["He argued back", "He was patient and prayed for them to be guided", "He ignored them completely", "He asked his companions to respond"], correct: 1, explanation: "When people threw stones at the Prophet ﷺ, the Angel Jibreel offered to punish them. The Prophet ﷺ refused and prayed: 'O Allah, guide my people.' This is the best example of forgiveness!", xp: 10 },
  { question: "What is 'backbiting' (gheebah) and is it allowed in Islam?", options: ["Talking about someone's good qualities — it is fine", "Saying something bad about someone behind their back — it is forbidden", "Joking with friends — it is allowed", "Telling the truth about someone — it is fine"], correct: 1, explanation: "Backbiting (gheebah) means saying something bad about someone behind their back — even if it is true. Allah compares it to eating the flesh of your dead brother (49:12). It is forbidden!", xp: 10 },
  { question: "Why does Islam tell us to lower our gaze (not stare at things we should not see)?", options: ["It saves our eyesight", "It protects the heart and is a command from Allah", "It is only for adults to think about", "It is just recommended, not important"], correct: 1, explanation: "Allah commands us to lower our gaze (24:30-31). Looking at things we should not see hardens the heart and leads to sins. Guarding our gaze brings blessing and purity to our life.", xp: 10 },
  { question: "How was the Prophet ﷺ described in terms of his generosity?", options: ["He saved money carefully", "'More generous than the flowing wind'", "He only gave to the poor", "Generous only in Ramadan"], correct: 1, explanation: "The Prophet ﷺ was described as 'more generous than the flowing wind'. Islam loves generosity — even a smile, sharing food, or removing something dangerous from a path is a form of charity!", xp: 10 },
  { question: "How should a Muslim behave on social media and the internet?", options: ["You can say anything online, no one is watching", "Apply Islamic manners — no lying, no bullying, no inappropriate content", "Different rules apply online", "Only adults need to think about this"], correct: 1, explanation: "Allah sees everything — online or offline! Islamic manners of speech, honesty, and kindness apply everywhere. No bullying, lying, or being mean online is ever acceptable for a Muslim.", xp: 10 },
  { question: "If a Muslim hurts someone, what should they do?", options: ["Pretend it did not happen", "Apologise sincerely and ask Allah for forgiveness", "Hope the person forgets", "Only make du'a without apologising"], correct: 1, explanation: "Islam teaches us to say sorry sincerely when we wrong someone and to try to make it right. The Prophet ﷺ said: settle things before the Day of Judgement, when all wrongs must be repaid!", xp: 10 },
  { question: "What is the best way to make your parents truly happy?", options: ["Expensive presents", "Money", "Good behaviour, obedience, kindness, and du'a for them", "Cooking for them only"], correct: 2, explanation: "The best gift to parents is good character, obedience, kindness, helping them, and making du'a: 'My Lord, have mercy on them as they raised me when I was small.' (Quran 17:24)", xp: 10 },
  { question: "What does Islam say about keeping our promises?", options: ["Promises only matter in big things", "Always keep your promises — breaking them is a sign of hypocrisy", "Promises to non-Muslims don't count", "It is fine to forget small promises"], correct: 1, explanation: "The Prophet ﷺ said the signs of a hypocrite include breaking promises. A true Muslim always keeps their word — with Muslims and non-Muslims alike. Your word is your honour!", xp: 10 },
];

// ─── CHILD TOPIC QUESTIONS MAP ────────────────────────────────────────────────
export const CHILD_TOPIC_QUESTIONS: Record<string, Question[]> = {
  quran: childQuranQuestions,
  duas: childDuasQuestions,
  manners: childMannersQuestions,
  seerah: childQuranQuestions,   // fallback to quran questions for now
  tafseer: childQuranQuestions,
  review: childQuranQuestions,
};

export function getChildQuestionsForLesson(topicId: string, lessonIndex: number, count = 10): Question[] {
  const childBank = CHILD_TOPIC_QUESTIONS[topicId];
  if (childBank) {
    const start = (lessonIndex * count) % childBank.length;
    const end = start + count;
    if (end <= childBank.length) return childBank.slice(start, end);
    return [...childBank.slice(start), ...childBank.slice(0, end - childBank.length)];
  }
  // Fall back to adult questions for topics without a child version
  return getQuestionsForLesson(topicId, lessonIndex, count);
}
