export interface LessonMeta {
  title: string;
  objective: string;
}

export const TOPIC_LESSONS: Record<string, LessonMeta[]> = {
  // ── Journey 1: The Noble Quran ────────────────────────────────────────────
  quran: [
    { title: "Introduction to the Quran", objective: "Discover what the Quran is, how it was revealed, and why it holds the highest place in a Muslim's life." },
    { title: "Structure of the Quran", objective: "Learn how the Quran is organised into surahs, ayaat, juz', and hizb — and what each term means." },
    { title: "The Key Surahs", objective: "Explore the most important and frequently recited surahs used in daily Muslim life and prayer." },
    { title: "The Heart of the Quran", objective: "Understand why Surah Ya-Sin is called the heart of the Quran and when it should be recited." },
    { title: "Surahs of Protection", objective: "Learn about Al-Mu'awwidhatayn (Al-Falaq and An-Nas), Ayat al-Kursi, and their protective power." },
    { title: "The Art of Tajweed", objective: "Discover the rules of Tajweed and why precise pronunciation is a command from Allah ﷻ." },
    { title: "Reading with Meaning", objective: "Move beyond recitation to understanding what you are reading — reflecting on the words of Allah ﷻ." },
    { title: "Hifz: Memorising the Quran", objective: "Learn about the immense blessing of memorising the Quran and proven techniques to begin." },
    { title: "Rewards of Recitation", objective: "Discover the immense spiritual rewards promised by the Prophet ﷺ for engaging with the Quran daily." },
    { title: "Etiquette with the Quran", objective: "Learn the proper Islamic etiquette for handling, reciting, and showing respect to the Quran." },
    { title: "The Quran in Daily Prayer", objective: "Understand which surahs and verses are recited in Salah and the wisdom behind their selection." },
    { title: "The Quran: A Way of Life", objective: "See how the Quran provides complete guidance for every aspect of a Muslim's life." },
    { title: "The Miracles of the Quran", objective: "Learn about the Quran's linguistic miracles and why it remains the eternal challenge to humanity." },
    { title: "Makki and Madani Surahs", objective: "Understand the difference between surahs revealed in Makkah and Madinah and their distinctive themes." },
    { title: "The Quran's Preservation", objective: "Discover how Allah ﷻ preserved the Quran through memorisation, writing, and the process of compilation." },
    { title: "Reflection (Tadabbur) on the Quran", objective: "Learn the Islamic methodology of deep reflection on Quranic verses and its transformative power." },
    { title: "Blessings of Surah Al-Kahf", objective: "Discover the profound lessons and weekly Sunnah rewards of Surah Al-Kahf." },
    { title: "The Last Ten Surahs", objective: "Study the short yet powerful surahs of Juz Amma and their regular use in Salah." },
    { title: "Improving Your Quranic Recitation", objective: "Practical steps for improving your recitation with proper makhaarij, rhythm, and tajweed rules." },
    { title: "The Quran: Your Companion for Life", objective: "A final reflection on building a lifelong, transformative relationship with the words of Allah ﷻ." },
  ],

  // ── Journey 2: Daily Duas & Adhkar ───────────────────────────────────────
  duas: [
    { title: "What Is Du'a?", objective: "Understand what supplication is, why the Prophet ﷺ called it the essence of worship, and when Allah answers." },
    { title: "Duas Before and After Eating", objective: "Master the taught supplications for beginning and ending a meal in the Sunnah way." },
    { title: "Duas for Purification", objective: "Learn the duas for entering and leaving the toilet, beginning wudu, and completing ghusl." },
    { title: "Duas During Prayer", objective: "Discover the supplications made at different points within the Salah itself." },
    { title: "Morning Adhkar", objective: "Learn the morning remembrances that protect, bless, and set the right intention for your day." },
    { title: "Evening Adhkar", objective: "Discover the evening remembrances that close the day in the remembrance of Allah ﷻ." },
    { title: "Duas for Sleeping and Waking", objective: "Learn the Prophet's ﷺ taught supplications before sleeping and upon waking each morning." },
    { title: "Duas When Entering and Leaving Home", objective: "Understand the protective Sunnah duas when leaving and returning to your home." },
    { title: "Duas for Travel", objective: "Master the supplications for safe, blessed travel by any means of transport." },
    { title: "Duas for the Masjid and Market", objective: "Learn specific duas for entering and leaving the masjid and navigating the marketplace." },
    { title: "Duas in Times of Hardship", objective: "Learn powerful duas for facing difficulties, grief, anxiety, and loss with faith." },
    { title: "Duas for Forgiveness", objective: "Master Sayyidul Istighfar and other comprehensive duas for seeking Allah's pardon." },
    { title: "Duas from the Prophets", objective: "Learn the heartfelt duas made by the Prophets in the Quran — and what we can take from them." },
    { title: "Duas for the Family", objective: "Discover supplications for spouse, children, parents, and those you love." },
    { title: "Duas for the Sick", objective: "Learn how to make dua for yourself and others when facing illness, citing ruqyah principles." },
    { title: "Duas for Special Occasions", objective: "Master duas for Ramadan, Laylat al-Qadr, Eid, marriage, and life's major moments." },
    { title: "Duas for Protection", objective: "Learn the comprehensive duas for protection from Shaytan, evil eye, and harm." },
    { title: "Duas for Knowledge and Guidance", objective: "Discover supplications for increasing knowledge, wisdom, and staying on the straight path." },
    { title: "Tahajjud and Night Duas", objective: "Learn the special supplications of the night prayer and when Allah descends to the lower heavens." },
    { title: "Living in Constant Remembrance", objective: "Learn how to make dhikr a natural, flowing part of every moment of your day." },
  ],

  // ── Journey 3: Islamic Manners ────────────────────────────────────────────
  manners: [
    { title: "The Importance of Good Character", objective: "Understand why the Prophet ﷺ said he was sent to perfect good character and what akhlaq really means." },
    { title: "Honesty and Trustworthiness", objective: "Learn about the quality of siddiq and why the Prophet ﷺ was called Al-Amin before prophethood." },
    { title: "Respect for Parents and Elders", objective: "Discover the extraordinary rank of parents in Islam and the exact duties owed to them." },
    { title: "The Islamic Greeting (Salaam)", objective: "Master the full Islamic greeting, its etiquette, and the rewards promised for spreading salaam." },
    { title: "Table Manners and Eating Etiquette", objective: "Learn every Sunnah practice around food, drink, and sharing meals with others." },
    { title: "Social Etiquette and Visiting", objective: "Understand Islamic manners for visiting others, hosting guests, and maintaining community ties." },
    { title: "Controlling Anger and Patience", objective: "Discover the Islamic strategies for managing anger — and why the Prophet ﷺ repeated 'Do not be angry' three times." },
    { title: "Generosity and Avoiding Waste", objective: "Learn the Islamic balance between generous giving and avoiding the sin of israf (extravagance)." },
    { title: "Cleanliness in Islam", objective: "Learn about the Islamic emphasis on physical and spiritual purity — 'cleanliness is half of faith'." },
    { title: "Lowering the Gaze", objective: "Understand the Islamic ruling and wisdom behind guarding one's gaze and practising modesty." },
    { title: "The Rights of Neighbours", objective: "Discover the extraordinary rights Islam gives to neighbours — up to 40 houses in each direction." },
    { title: "Kindness to Animals", objective: "Learn the Islamic responsibility towards animals and the rewards the Prophet ﷺ described for showing them mercy." },
    { title: "Speaking Only Good", objective: "Understand the principle of saying good or remaining silent, and the immense damage an unguarded tongue can cause." },
    { title: "Keeping Family Ties", objective: "Learn about silat al-rahm (keeping ties of kinship) and the severe warning against cutting family ties." },
    { title: "The Rights of the Poor", objective: "Discover your Islamic duty towards the poor, needy, and those in hardship in your community." },
    { title: "Being a Good Guest and Host", objective: "Learn the complete etiquette of Islamic hospitality — what a guest owes and what a host must provide." },
    { title: "Islamic Ethics Online", objective: "Apply Islamic principles of speech, modesty, and truthfulness to social media and online behaviour." },
    { title: "Forgiveness and Letting Go", objective: "Learn the Islamic virtue of pardoning others and the extraordinary reward Allah ﷻ promises those who forgive." },
    { title: "Community Responsibility", objective: "Understand the Sunnah concept of the Muslim community as one body and your active role in its wellbeing." },
    { title: "Bringing It All Together", objective: "A comprehensive review of Islamic character and manners with a practical commitment to daily improvement." },
  ],

  // ── Journey 4: The Prophet's Life ﷺ ─────────────────────────────────────
  seerah: [
    { title: "Arabia Before Islam", objective: "Understand the social, political, and moral state of Arabia before the birth of the Prophet ﷺ." },
    { title: "The Birth and Early Life", objective: "Learn about the miraculous year of the Prophet's ﷺ birth and his orphaned, blessed childhood." },
    { title: "Youth and Character", objective: "Discover the remarkable character of Al-Amin in his youth — before the first revelation arrived." },
    { title: "Marriage to Khadijah (RA)", objective: "Learn about the Prophet's ﷺ blessed marriage, Khadijah's role, and why she was the greatest of women." },
    { title: "The First Revelation", objective: "Experience the momentous night in Cave Hira when Jibreel (AS) first appeared to the Prophet ﷺ." },
    { title: "The Early Muslims and Persecution", objective: "Discover who the first Muslims were and how they endured brutal persecution with steadfast faith." },
    { title: "Migration to Abyssinia", objective: "Understand why the Prophet ﷺ sent early Muslims to Christian Abyssinia and what this teaches about seeking justice." },
    { title: "The Year of Grief and Isra wal Mi'raj", objective: "Learn about the deaths of Khadijah (RA) and Abu Talib, and the miraculous Night Journey that followed." },
    { title: "The Hijra to Madinah", objective: "Follow the Prophet's ﷺ migration in detail — the planning, the journey, and the arrival." },
    { title: "Building the Islamic State", objective: "How the Prophet ﷺ built the first Muslim community: the masjid, the brotherhood, and the constitution." },
    { title: "Battles of Badr and Uhud", objective: "Learn from the first major battles in Islamic history — triumph at Badr, lessons at Uhud." },
    { title: "The Conquest of Makkah", objective: "Follow the peaceful liberation of Makkah and witness the Prophet's ﷺ extraordinary mercy to his enemies." },
    { title: "The Farewell Sermon", objective: "Study the Prophet's ﷺ final sermon — the most important speech in Islamic history." },
    { title: "The Companions (Sahabah)", objective: "Meet the key companions who sacrificed everything for Islam and shaped the early Ummah." },
    { title: "The Legacy of the Prophet ﷺ", objective: "Reflect on what the Prophet ﷺ left for all of humanity — until the Day of Judgment." },
    { title: "Women in Early Islam", objective: "Discover the remarkable women who shaped early Islam — Aisha, Fatimah, Asma, and others." },
    { title: "The Battles of the Trench and Khaybar", objective: "Learn from the defensive Battle of the Trench and the subsequent expedition to Khaybar." },
    { title: "The Treaty of Hudaybiyyah", objective: "Understand the 'clear victory' that didn't look like one — and why it changed everything for the Muslims." },
    { title: "The Prophet ﷺ's Treatment of Non-Muslims", objective: "Understand the Prophet's ﷺ extraordinary conduct with non-Muslims — justice, mercy, and coexistence." },
    { title: "Living the Sunnah Today", objective: "Bring the Seerah to life: practical ways to revive the Prophet's ﷺ character in everyday modern living." },
  ],

  // ── Journey 5: Stories of the Prophets ───────────────────────────────────
  prophets: [
    { title: "Believing in the Prophets", objective: "Understand the Islamic belief (aqeedah) regarding prophethood — who the prophets were and their essential qualities." },
    { title: "Adam and Hawa (AS)", objective: "Learn about the creation of the first humans, life in Jannah, and the beginning of humanity on earth." },
    { title: "Nuh (AS) and the Ark", objective: "Follow the remarkable story of Nuh (AS) — 950 years of calling his people and building the great ark." },
    { title: "Ibrahim (AS): Friend of Allah", objective: "Learn about the father of monotheism, his extraordinary tests, and why Allah took him as a close friend." },
    { title: "Musa (AS) and the Pharaoh", objective: "Follow the epic story of Musa (AS) — from the Nile to Mount Sinai and the parting of the sea." },
    { title: "Dawud and Sulayman (AS)", objective: "Discover the prophets who were also kings, gifted with extraordinary blessings and divine abilities." },
    { title: "Yunus and Ayyub (AS)", objective: "Learn from the stories of patience, prayer, and redemption — inside a whale and through years of suffering." },
    { title: "Isa ibn Maryam (AS)", objective: "Understand the Islamic belief about Isa (AS), his miraculous birth, and his role before the Day of Judgment." },
    { title: "The Seal of the Prophets ﷺ", objective: "Understand why Muhammad ﷺ is the final prophet and what this means for all of humanity." },
    { title: "Lessons from the Prophets", objective: "Draw timeless practical lessons from the lives of all the prophets for your life today." },
    { title: "Yusuf (AS): The Complete Story", objective: "Journey through the detailed story of Yusuf (AS) — envy, slavery, prison, and ultimate triumph." },
    { title: "Musa (AS) in the Desert", objective: "Follow Musa (AS) after leaving Egypt — the years in Madyan and how they shaped him before prophethood." },
    { title: "Hud and Salih (AS)", objective: "Learn about the prophets sent to the powerful nations of 'Ad and Thamud and how they were destroyed." },
    { title: "Lut (AS) and the Destruction of Sodom", objective: "Understand the story of Lut (AS), the crime of his people, and the mercy shown in warning them." },
    { title: "Zakariyya and Yahya (AS)", objective: "Learn about the elderly prophet given a miraculous son — Yahya (AS) — and the remarkable duas that brought him." },
    { title: "Idris and Ilyas (AS)", objective: "Explore the stories of Idris (AS) raised to a high place and Ilyas (AS) who struggled alone against an entire nation." },
    { title: "Shu'ayb and Dhul Kifl (AS)", objective: "Learn about these prophets and the universal message of justice and accountability they carried." },
    { title: "The Prophets and Their Tests", objective: "Reflect on the consistent pattern of prophets being tested — and how each trial increased their rank." },
    { title: "Common Lessons Across All Prophets", objective: "Draw out the unifying themes: patience, trust in Allah, community building, and victory after hardship." },
    { title: "Living the Prophetic Legacy", objective: "Apply the practical lessons of the prophets to your daily life as a believer today." },
  ],

  // ── Journey 6: Islamic History ────────────────────────────────────────────
  history: [
    { title: "The Rightly Guided Caliphs", objective: "Introduction to the four caliphs who followed the Prophet ﷺ and why they are called 'Rightly Guided'." },
    { title: "Abu Bakr al-Siddiq (RA)", objective: "Learn how the first caliph held the Ummah together in the most critical moments after the Prophet's ﷺ death." },
    { title: "Umar ibn al-Khattab (RA)", objective: "Discover how the second caliph built the Islamic state into a world power through justice and wisdom." },
    { title: "Uthman and Ali (RA)", objective: "Learn about the third and fourth caliphs, their achievements, and the trials that tested the Ummah." },
    { title: "The Umayyad Caliphate", objective: "Understand Islam's first hereditary dynasty and the remarkable expansion to Spain and Central Asia." },
    { title: "The Abbasid Golden Age", objective: "Explore the height of Islamic civilisation when Baghdad led the world in art, science, and scholarship." },
    { title: "The House of Wisdom", objective: "Discover Bayt al-Hikmah and the Islamic Golden Age contributions that shaped world knowledge." },
    { title: "Al-Andalus: Islam in Spain", objective: "Learn about 800 years of flourishing Muslim civilisation on European soil." },
    { title: "The Crusades and Salahuddin", objective: "Understand the Crusades and the Muslim response under the great Salahuddin al-Ayyubi." },
    { title: "The Mongol Invasion", objective: "Learn how the Mongols devastated Baghdad and how Islam survived and eventually transformed the Mongols." },
    { title: "The Ottoman Empire", objective: "Explore six centuries of Islamic governance that spanned three continents." },
    { title: "Muslim Scholars and Scientists", objective: "Meet the giants of Islamic learning whose discoveries changed the course of human civilisation." },
    { title: "The Fall of the Ottoman Empire", objective: "Understand the events that ended the last Islamic caliphate and their impact on the Muslim world." },
    { title: "Islam in the Modern World", objective: "Survey the Muslim world from colonialism to the present day and the challenges and opportunities ahead." },
    { title: "Women in Islamic History", objective: "Highlight the remarkable women scholars, rulers, and leaders throughout 1,400 years of Islamic history." },
    { title: "Islamic Art, Architecture, and Culture", objective: "Explore the rich Islamic contribution to art, calligraphy, architecture, and aesthetic beauty." },
    { title: "The Spread of Islam in Africa", objective: "Learn how Islam spread across Africa through trade, scholars, and grassroots movements of faith." },
    { title: "Islam in South and Southeast Asia", objective: "Discover how Islam came to the Indian subcontinent and Southeast Asia and its enduring impact." },
    { title: "Muslim Contributions to Science", objective: "Deep-dive into Muslim contributions to astronomy, medicine, mathematics, and chemistry." },
    { title: "Islam in the Contemporary Era", objective: "Survey the Muslim world today — challenges, resilience, scholarship, and the global Ummah." },
  ],

  // ── Journey 7: Arabic Language I ─────────────────────────────────────────
  arabic: [
    { title: "The Arabic Alphabet — Part 1", objective: "Begin your Arabic journey with the first seven letters, their shapes, and the sounds they make." },
    { title: "The Arabic Alphabet — Part 2", objective: "Continue with the next group of Arabic letters, building your recognition and pronunciation." },
    { title: "The Arabic Alphabet — Part 3", objective: "Learn the third set of Arabic letters — you are more than halfway through the alphabet." },
    { title: "The Arabic Alphabet — Part 4", objective: "Complete the Arabic alphabet with the final letters, giving you the full 28-letter foundation." },
    { title: "Connecting Arabic Letters", objective: "Understand how Arabic letters connect in words and how most letters change form in different positions." },
    { title: "Short Vowels (Harakat)", objective: "Learn the three short vowels — fatha (a), kasra (i), damma (u) — and how they change word meanings." },
    { title: "The Definite Article (Al)", objective: "Master 'Al' (the), the sun and moon letter categories, and how it attaches to Arabic nouns." },
    { title: "Essential Islamic Vocabulary", objective: "Learn the most important Islamic terms in Arabic — the words you will encounter in worship every day." },
    { title: "Pronouns in Arabic", objective: "Learn personal pronouns — I, you, he, she, we, they — and how they work in Arabic sentences." },
    { title: "Greetings and Daily Phrases", objective: "Master practical Islamic greetings and the everyday phrases a Muslim uses in conversation." },
    { title: "Names of Allah (Asma ul Husna)", objective: "Learn the 99 beautiful names of Allah ﷻ, their meanings, and how to incorporate them into dhikr." },
    { title: "The Arabic Root System", objective: "Unlock the secret of Arabic: understand the three-letter root system that gives Arabic its unique structure." },
    { title: "Core Quranic Vocabulary", objective: "Learn the 100 most frequently used words in the Quran — understanding them unlocks a huge portion of the text." },
    { title: "Asking Questions in Arabic", objective: "Master the question words: man (who), ma (what), mata (when), ayna (where), kayfa (how), limadha (why)." },
    { title: "Quranic Vocabulary: Al-Fatiha", objective: "Go through every word of Surah Al-Fatiha in Arabic — the surah you recite in every prayer." },
    { title: "Quranic Vocabulary: Short Surahs", objective: "Study key vocabulary from the Juz' Amma (30th juz') — the surahs most commonly memorised and recited." },
    { title: "Arabic in Prayer (Salah)", objective: "Understand the meaning of every Arabic phrase and dua recited during the five daily prayers." },
    { title: "Arabic Numbers", objective: "Learn Arabic numbers from 1–100 and how to express quantities in everyday Islamic contexts." },
    { title: "Vocabulary of the Prophets' Stories", objective: "Key Arabic words from the Quranic stories of the prophets — expanding your Quranic comprehension." },
    { title: "Simple Arabic Sentences", objective: "Combine what you have learned to form basic Arabic sentences about Islamic topics." },
  ],

  // ── Journey 8: Arabic Language II ────────────────────────────────────────
  arabic2: [
    { title: "Understanding Hadith Arabic", objective: "Learn the common Arabic patterns and vocabulary that appear most frequently in hadith collections." },
    { title: "Arabic Verbs — Introduction", objective: "Understand the past, present, and command verb forms and how they work in Arabic sentences." },
    { title: "Reading Islamic Arabic Phrases", objective: "Practise reading short Islamic phrases and Quranic extracts, building your fluency." },
    { title: "Arabic Revision and Consolidation", objective: "A review of key vocabulary, grammar, Quranic terms, and daily phrases from Arabic I." },
    { title: "Long Vowels and Tanwin", objective: "Master the long vowels and nunation marks that change the sound and meaning of Arabic words." },
    { title: "Masculine and Feminine in Arabic", objective: "Learn how Arabic marks gender in nouns, adjectives, and verbs and how to apply it correctly." },
    { title: "Dual Forms in Arabic", objective: "Understand the Arabic dual — how to form and use words referring to exactly two things." },
    { title: "Plurals in Arabic", objective: "Learn the complex but essential Arabic plural system — both sound and broken plurals." },
    { title: "Arabic Adjectives and Agreement", objective: "Learn how adjectives follow their nouns in Arabic, agreeing in gender, number, and definiteness." },
    { title: "Prepositions in Arabic", objective: "Master the common Arabic prepositions and how they change the meaning of sentences." },
    { title: "Simple Past Tense Sentences", objective: "Build complete past tense sentences in Arabic using patterns from the Quran and hadith." },
    { title: "Present and Future Tense", objective: "Form present and future tense sentences in Arabic and understand verb conjugation patterns." },
    { title: "Negative Sentences in Arabic", objective: "Learn how to negate statements and commands in Arabic using lan, lam, la, and laysa." },
    { title: "Reading Surah Al-Asr in Arabic", objective: "Read, understand, and reflect on every word of Surah Al-Asr in Arabic." },
    { title: "Reading Surah Al-Ikhlas in Arabic", objective: "Go through every word of Surah Al-Ikhlas — the surah worth a third of the Quran." },
    { title: "Arabic of the Five Pillars", objective: "Learn the specific Arabic terms and phrases related to each of the Five Pillars in depth." },
    { title: "Arabic of Salah — Every Word", objective: "Go word by word through every phrase said in the five daily prayers." },
    { title: "Building a Quranic Vocabulary List", objective: "Systematic approach to learning the top 200 Quranic words by frequency and how to memorise them." },
    { title: "Reading Arabic Without Harakat", objective: "Practise reading unvocalised Arabic text — the form you encounter in most books and Qurans." },
    { title: "Arabic Learning — Next Steps", objective: "A roadmap for continuing your Arabic journey with recommended resources and daily habits." },
  ],

  // ── Journey 9: Islamic Law I ──────────────────────────────────────────────
  fiqh: [
    { title: "Introduction to Islamic Law", objective: "Understand what fiqh is, its four primary sources, and why studying it is an obligation upon every Muslim." },
    { title: "The Five Pillars of Islam", objective: "A deep dive into the five foundational pillars that structure every Muslim's life and worship." },
    { title: "Purification (Taharah)", objective: "Master wudu, ghusl, tayammum, and the types of impurity that must be removed before worship." },
    { title: "Salah — Foundations", objective: "Learn the conditions, pillars, and obligatory elements that make each prayer valid before Allah ﷻ." },
    { title: "Salah — Times and Types", objective: "Understand the five daily prayers, Friday (Jumuah), Eid, and the Sunnah and voluntary prayers." },
    { title: "Zakat: Obligatory Charity", objective: "Learn the nisab, rate, categories of wealth, and who is eligible to receive zakat." },
    { title: "Fasting in Ramadan (Sawm)", objective: "Understand the rules, exemptions, things that break the fast, and the spiritual purpose of fasting." },
    { title: "Hajj and Umrah", objective: "Learn the pillars of Hajj, the rites of Umrah, and the conditions that make Hajj obligatory." },
    { title: "Halal and Haram Food", objective: "Master Islamic dietary law: what is permitted, what is forbidden, and how to verify food is halal." },
    { title: "Islamic Finance: Avoiding Riba", objective: "Understand why riba (interest/usury) is forbidden and what halal financial alternatives exist." },
    { title: "Family Law: Marriage (Nikah)", objective: "Learn the requirements for a valid nikah, the rights of spouses, and the wisdom in Islamic marriage law." },
    { title: "Family Law: Divorce and After", objective: "Understand talaq, khul', the iddah waiting period, and children's rights in Islamic family law." },
    { title: "The Four Madhabs", objective: "Understand the four Sunni schools of jurisprudence, their founders, and how to follow one correctly." },
    { title: "Fiqh of Worship in Detail", objective: "Deeper rulings on prayer, fasting, zakat, and hajj — the fine details every Muslim should know." },
    { title: "Business Ethics in Islam", objective: "Learn the Islamic principles governing trade, contracts, forbidden transactions, and marketplace conduct." },
    { title: "Rights and Responsibilities", objective: "Understand the rights of Allah, yourself, your family, your community, and all of creation." },
    { title: "Contemporary Fiqh Issues", objective: "Learn how Islamic scholars address modern questions: halal investing, organ donation, social media conduct." },
    { title: "Revision: Essential Islamic Rulings", objective: "A review of the most important rulings from all fiqh topics — consolidating your knowledge." },
    { title: "Worship in Special Circumstances", objective: "Learn Islamic rulings for prayer, fasting, and worship during illness, travel, and disability." },
    { title: "Fiqh Review — Essentials", objective: "A final comprehensive review of the most critical rulings every Muslim must know and act upon." },
  ],

  // ── Journey 10: Islamic Law II ────────────────────────────────────────────
  fiqh2: [
    { title: "Introduction to Usul al-Fiqh", objective: "Discover the principles of Islamic jurisprudence — the methodology scholars use to derive rulings from sources." },
    { title: "The Maqasid al-Shariah", objective: "Learn the five objectives of Islamic law: preservation of religion, life, intellect, lineage, and wealth." },
    { title: "Secondary Sources of Islamic Law", objective: "Understand consensus (ijma), analogy (qiyas), custom (urf), and other secondary juristic sources." },
    { title: "Ijtihad and Fatwa", objective: "Learn what ijtihad is, who is qualified to perform it, and how fatwas are issued in the modern world." },
    { title: "Islamic Medical Ethics", objective: "Apply Islamic principles to modern medical questions: organ donation, end-of-life care, and IVF." },
    { title: "Islamic Environmental Ethics", objective: "Learn the Islamic concept of khalifah (stewardship) and our responsibility to the natural world." },
    { title: "Rights of Non-Muslims in Islam", objective: "Understand the detailed Islamic rights of non-Muslim citizens and guests under Islamic governance." },
    { title: "Waqf — Islamic Endowments", objective: "Discover the Islamic institution of permanent charitable endowment and its historical impact." },
    { title: "Islamic Inheritance Law (Mirath)", objective: "Learn the Quranic system of inheritance — the shares, the heirs, and the wisdom behind it." },
    { title: "Islamic Contracts (Uqud)", objective: "Understand the essential elements of valid Islamic contracts and the elements that make them forbidden." },
    { title: "Rulings on Debts and Loans", objective: "Master Islamic rulings on lending, borrowing, documentation of debt, and the etiquette around it." },
    { title: "Partnership and Business Law", objective: "Learn Islamic partnership structures (musharakah, mudarabah) used in halal business today." },
    { title: "Banking and Islamic Finance Today", objective: "Survey modern Islamic finance products — sukuk, murabaha, ijara — and how they work." },
    { title: "Rulings on Digital Transactions", objective: "Apply Islamic principles to cryptocurrencies, online transactions, and digital commerce." },
    { title: "Fiqh of the Family — Child Rights", objective: "Learn the rights of children in Islamic law from birth, naming, education, to adulthood." },
    { title: "Fiqh of Citizenship and Governance", objective: "Understand Islamic principles of governance, consultation (shura), and civic responsibility." },
    { title: "The Fiqh of Oaths and Vows", objective: "Understand the Islamic rulings on oaths (qasam) and vows (nadhr) — when they bind and their expiation." },
    { title: "Fiqh of Mosques (Ahkam al-Masajid)", objective: "Learn the rights, etiquette, and rulings specific to mosques and the sanctity they carry." },
    { title: "Fiqh of Entertainment and Leisure", objective: "Learn what Islam says about music, art, sport, and permissible forms of entertainment." },
    { title: "Comprehensive Fiqh Review", objective: "A final review of Fiqh II principles and how to continue applying them to an ever-changing world." },
  ],

  // ── Journey 11: The Prayer (Salah) ───────────────────────────────────────
  salah: [
    { title: "The Importance of Salah", objective: "Understand why Salah is the pillar of the deen and the first thing we will be asked about on Yawm al-Qiyamah." },
    { title: "The Conditions of Prayer", objective: "Learn the prerequisites for a valid prayer: purity, awrah, Qibla, intention, and correct prayer time." },
    { title: "The Pillars (Arkaan) of Salah", objective: "Master the obligatory components that, if missed, completely invalidate your prayer." },
    { title: "The Wajibat of Salah", objective: "Understand the obligatory elements that require sujood as-sahw (prostration of forgetfulness) if missed." },
    { title: "Prayer Times and Their Wisdom", objective: "Learn the five daily prayer windows, the best time to pray within each, and the wisdom behind their timing." },
    { title: "The Movements of Salah", objective: "Follow each position from Qiyam to Salam with their recitations, reflecting on what each position means." },
    { title: "What Invalidates Prayer", objective: "Learn the actions that break Salah — speaking, laughing, intentional movement, breaking wudu — and how to avoid them." },
    { title: "Sunnah and Voluntary Prayers", objective: "Discover the rawatib (regular Sunnah prayers), Tahajjud, Duha, and how extra prayers build closeness to Allah ﷻ." },
    { title: "Jumuah (Friday Prayer)", objective: "Learn the obligations, conditions, khutbah requirements, and etiquette of the Friday congregational prayer." },
    { title: "Prayer for the Traveller (Qasr and Jam')", objective: "Learn the shortening and combining of prayers during travel — who qualifies and exactly how to do it." },
    { title: "Prayer During Illness", objective: "Learn how to pray when you cannot stand, sit, or complete normal prayer movements." },
    { title: "Eid Prayers", objective: "Learn the prayer of the two Eids — the takbeers, the khutbah, and its special ruling." },
    { title: "The Witr Prayer", objective: "Understand the witr prayer, its ruling (wajib or Sunnah), its time, and the du'a al-qunut." },
    { title: "Salah in Congregation (Jama'ah)", objective: "Learn the rulings, positions, and the immense rewards of praying in congregation." },
    { title: "Sajdah of Recitation", objective: "Learn which Quranic verses require a prostration when recited or heard and how to perform it." },
    { title: "The Prayer of Istikharah", objective: "Learn the full Istikharah prayer, its dua, and how to correctly seek and understand the guidance received." },
    { title: "Making Up Missed Prayers (Qada)", objective: "Learn the Islamic position on making up missed prayers and how to systematically work through them." },
    { title: "Common Mistakes in Salah", objective: "Identify and correct the most common errors made in prayer that affect its validity or quality." },
    { title: "Achieving Khushu' in Prayer", objective: "Learn the practical steps for achieving true presence of heart and humility in your salah." },
    { title: "Building a Lifelong Prayer Habit", objective: "Strategies from the Sunnah for never missing a prayer and making Salah the anchor of your day." },
  ],

  // ── Journey 12: Dhikr, Fasting & Ramadan ─────────────────────────────────
  dhikr_ramadan: [
    { title: "Why Dhikr Nourishes the Soul", objective: "Understand why the Quran says 'Verily in the remembrance of Allah do hearts find rest' (13:28)." },
    { title: "Morning Adhkar (Sabah)", objective: "Learn the complete morning routine of remembrance with their specific wording, frequency, and rewards." },
    { title: "Evening Adhkar (Masa)", objective: "Master the evening remembrances that seal your day in Allah's ﷻ protection and mercy." },
    { title: "Dhikr After Every Salah", objective: "Learn the exact post-prayer dhikr taught by the Prophet ﷺ — SubhanAllah, Alhamdulillah, Allahu Akbar." },
    { title: "The Power of Istighfar", objective: "Discover why seeking forgiveness is one of the most powerful acts of worship and when it should be said." },
    { title: "Dhikr Throughout the Day", objective: "Learn short yet powerful phrases for every daily activity: eating, dressing, travelling, and more." },
    { title: "The 99 Beautiful Names of Allah", objective: "Learn Allah's ﷻ Asma ul-Husna — their meanings and how calling upon them transforms your dhikr." },
    { title: "The Obligation and Virtue of Fasting", objective: "Understand when fasting Ramadan became obligatory, who must fast, and the extraordinary rewards promised." },
    { title: "The Pillars and Conditions of Sawm", objective: "Learn what makes a fast valid: the intention (niyyah), abstaining from all nullifiers, and the valid period." },
    { title: "What Breaks the Fast", objective: "Master the things that nullify the fast and the kaffarah (expiation) for deliberate violations." },
    { title: "The Sunnah of Ramadan", objective: "Discover the Prophet's ﷺ complete Ramadan routine: suhoor, iftar dua, tarawih, i'tikaf, and extra worship." },
    { title: "Laylat al-Qadr and the Last Ten Nights", objective: "Learn why the Night of Power (better than 1,000 months) must be sought and exactly how to make the most of it." },
    { title: "I'tikaf: Seclusion in the Masjid", objective: "Learn about the spiritual retreat of the last ten nights and its profound benefits for the believer." },
    { title: "Voluntary Fasts Beyond Ramadan", objective: "Learn the 6 fasts of Shawwal, Mondays and Thursdays, Day of Arafah, and Ashura." },
    { title: "The Spiritual Journey of Ramadan", objective: "Understand the three stages of Ramadan (mercy, forgiveness, freedom from Fire) and how to maximise each." },
    { title: "Tarawih and Night Worship", objective: "A practical guide to the night prayers of Ramadan and how to make them meaningful all year round." },
    { title: "Zakat al-Fitr", objective: "Learn the ruling, amount, and time for Zakat al-Fitr — the obligatory charity before Eid prayer." },
    { title: "Eid al-Fitr: Completing Ramadan", objective: "Learn the Sunnah practices of Eid day from ghusl to prayer to the etiquette of Islamic celebration." },
    { title: "Sustaining Ramadan All Year", objective: "How to carry the spiritual gains of Ramadan into the rest of the year through consistent practice." },
    { title: "Dhikr and Fasting: A Review", objective: "A comprehensive review of remembrance practices and fasting rulings — bringing it all together." },
  ],

  // ── Journey 13: Islamic Creed (Aqeedah) ──────────────────────────────────
  aqeedah: [
    { title: "The Six Pillars of Iman", objective: "Understand the six foundational beliefs every Muslim must hold — and what denying any one of them means." },
    { title: "Tawheed: The Oneness of Allah", objective: "Learn the three categories of Tawheed — Rububiyyah, Uluhiyyah, and Asma wa Sifat." },
    { title: "Belief in the Angels", objective: "Discover the nature, roles, and names of the angels — including Jibreel, Mikail, Israfeel, and Munkar and Nakeer." },
    { title: "Belief in the Divine Books", objective: "Learn about the scriptures Allah ﷻ revealed — the Tawrah, Injeel, Zabur, and the Quran." },
    { title: "Belief in All the Prophets", objective: "Understand the aqeedah obligation to believe in all prophets, their essential qualities, and the 25 named in the Quran." },
    { title: "Belief in the Day of Judgement", objective: "Learn the major and minor signs of the Hour, the stages of the Hereafter, and what happens after death." },
    { title: "Belief in Qadr (Divine Decree)", objective: "Understand the four levels of Qadr — knowledge, writing, will, and creation — and the peace it brings." },
    { title: "Shirk: The Greatest Sin", objective: "Learn what constitutes shirk, why it is the one unforgivable sin if died upon, and how to protect your Tawheed." },
    { title: "Tawheed in Practice", objective: "Learn how pure monotheism should shape every decision, relationship, and action in a Muslim's daily life." },
    { title: "Shirk in the Modern World", objective: "Identify subtle and major forms of shirk that appear in modern culture and how to protect against them." },
    { title: "The Nature of Allah's Attributes (Sifat)", objective: "Understand how Muslims affirm Allah's names and attributes without likening Him to creation." },
    { title: "Belief in the Unseen (Al-Ghayb)", objective: "Learn what the unseen includes — angels, jinn, paradise, hellfire — and how it shapes a believer's worldview." },
    { title: "The Jinn in the Quran and Sunnah", objective: "Learn what Islam teaches about jinn, their creation, their beliefs, and the protection available to believers." },
    { title: "Black Magic, Evil Eye, and Ruqyah", objective: "Understand the Islamic position on sihr (magic), 'ayn (evil eye), and the permissible Quranic cure (ruqyah)." },
    { title: "The Signs of the Day of Judgement", objective: "Study both minor and major signs of the Last Hour mentioned in the Quran and authentic hadith." },
    { title: "Life After Death — The Barzakh", objective: "Learn about the grave (its questions and trials), the blowing of the trumpet, and the stages before Qiyamah." },
    { title: "Jannah and Jahannam — Reality", objective: "Understand the detailed Quranic and hadith descriptions of Paradise and Hellfire." },
    { title: "The Mizan, the Sirat, and the Hisab", objective: "Learn about the scales of deeds, the bridge over Hell, and the account on the Day of Judgement." },
    { title: "How Aqeedah Protects a Believer", objective: "Understand how correct belief is a shield against extremism, doubt, and spiritual emptiness." },
    { title: "Living with Correct Belief", objective: "Bring all aqeedah knowledge together in a practical guide to living as a believer of firm, grounded faith." },
  ],

  // ── Journey 14: Hadith Sciences ───────────────────────────────────────────
  hadith: [
    { title: "What Is Hadith and Why It Matters", objective: "Understand what hadith is, how it differs from Quran, and why the Prophet's ﷺ sunnah is the second source of Islamic law." },
    { title: "The Isnad — Chain of Narrators", objective: "Learn what the chain of transmission (isnad) is and why Ibn al-Mubarak said 'The isnad is part of the religion.'" },
    { title: "Categories: Sahih, Hasan, Da'if", objective: "Understand the grading system for hadith — authentic, good, weak — and how scholars determined reliability." },
    { title: "The Six Major Hadith Collections", objective: "Learn about the Kutub al-Sittah (Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasa'i, Ibn Majah) and their reliability." },
    { title: "How Scholars Verified Narrators", objective: "Discover the science of Ilm al-Rijal (narrator criticism) — how scholars investigated thousands of narrators." },
    { title: "How to Cite and Use Hadith", objective: "Learn the proper format for citing hadith with collection name and number, and how to use them correctly." },
    { title: "The 40 Hadith of Imam al-Nawawi", objective: "Learn about Imam al-Nawawi's collection of 42 foundational hadith and their central role in Islamic education." },
    { title: "Hadith 1 — Actions by Intentions", objective: "'Actions are by intentions' — the most foundational hadith in Islam and its comprehensive implications." },
    { title: "Hadith 2 — The Path to Jannah", objective: "'Islam is built on five…' — the structure of Islamic practice as the Prophet ﷺ defined it." },
    { title: "Hadith 6 — Halal and Haram Are Clear", objective: "Understand the boundaries Allah has set and the wisdom of cautious avoidance of the doubtful." },
    { title: "Hadith 13 — Love for Your Brother", objective: "'Love for your brother what you love for yourself' — the social principle that builds Muslim community." },
    { title: "Hadith 17 — Ihsan in All Things", objective: "'Allah has decreed ihsan in all things' — a transformative hadith on excellence in every act." },
    { title: "Hadith 19 — Be Mindful of Allah", objective: "The comprehensive hadith 'Be mindful of Allah and He will protect you' with its multiple commands." },
    { title: "Hadith 24 — Forbidden Wrongs", objective: "Understanding the hadith that forbids wrongdoing to oneself and others — the rights of people in Islam." },
    { title: "Hadith 29 — Avoiding What You've Been Warned", objective: "'Avoid what I have forbidden and do what I have commanded' — the principle of prophetic obedience." },
    { title: "The Four Great Imams and Hadith", objective: "Learn how Imam Abu Hanifa, Malik, al-Shafi'i, and Ahmad ibn Hanbal approached and applied hadith." },
    { title: "Fabricated Hadith — Recognising False Reports", objective: "Understand what constitutes a fabricated hadith, famous examples, and why scholars fought to expose them." },
    { title: "Hadith in Everyday Muslim Life", objective: "Learn how to practically incorporate authentic hadith into worship, character, and daily decisions." },
    { title: "Memorising Hadith — A Practical Guide", objective: "Learn the proven techniques used by classical scholars to memorise hadith collections effectively." },
    { title: "Hadith Studies — Where to Go Next", objective: "A roadmap for continuing hadith studies: recommended books, scholars, and online resources." },
  ],

  // ── Journey 15: Islamic Character ────────────────────────────────────────
  character: [
    { title: "Why Character Is the Core of Islam", objective: "Understand the Prophet's ﷺ statement 'I was sent to perfect good character' and what this tells us." },
    { title: "Truthfulness (Sidq) and Its Rewards", objective: "Learn why truthfulness leads to righteousness and to Paradise, and how the Prophet ﷺ embodied Sidq." },
    { title: "Patience (Sabr) and Its Three Types", objective: "Discover the three types of Sabr — patience in obedience, avoiding sin, and in trials." },
    { title: "Generosity (Karam) in the Sunnah", objective: "Learn how the Prophet ﷺ was 'more generous than the flowing wind' and how generosity protects the heart." },
    { title: "Humility (Tawadu) Over Arrogance", objective: "Understand why Islam considers arrogance one of the most destructive traits and how humility elevates a person." },
    { title: "Controlling Anger in Islam", objective: "Learn 'Do not be angry' (repeated three times), the Islamic tools for managing anger, and what strength really means." },
    { title: "Gratitude (Shukr) — The Transformative Virtue", objective: "'If you are grateful, I will surely increase you' — learn what shukr means in practice and how to cultivate it." },
    { title: "Reliance on Allah (Tawakkul)", objective: "Understand the correct Islamic balance between taking means and trusting in Allah's outcome for your affairs." },
    { title: "Hope and Fear (Raja and Khawf)", objective: "Learn the Islamic balance between hoping for Allah's mercy and fearing His punishment — the wings of faith." },
    { title: "Love of Allah and the Prophet ﷺ", objective: "Understand what it means to truly love Allah and His Messenger — the signs and the fruits of that love." },
    { title: "Brotherhood and Sisterhood in Islam", objective: "Learn the rights of a Muslim upon another Muslim and the bond the Prophet ﷺ described as deeper than family." },
    { title: "Sincerity (Ikhlas) — The Soul of Every Act", objective: "Understand why every deed is judged by its intention and how to cultivate pure sincerity in worship." },
    { title: "Repentance (Tawbah) — The Gate Always Open", objective: "Learn the conditions of a valid repentance, why Allah loves those who return to Him, and how to start fresh." },
    { title: "The Disease of Envy (Hasad)", objective: "Understand the spiritual destruction caused by envy, its types, and the prophetic cures for it." },
    { title: "The Disease of Arrogance (Kibr)", objective: "Learn why arrogance is the barrier to Paradise and the practical steps to cultivate genuine humility." },
    { title: "The Disease of Love of Dunya", objective: "Understand the Islamic perspective on the world and how to live in it without being enslaved by it." },
    { title: "Contentment (Qana'ah) — The Hidden Treasure", objective: "Discover why contentment with Allah's decree is called a treasure that never runs out." },
    { title: "Mindfulness (Muraqabah) of Allah", objective: "Learn the concept of muraqabah — living as if you see Allah — and how it transforms every action." },
    { title: "The Righteous Companion", objective: "Understand the immense impact of companions on your character and the Sunnah guidance on choosing righteous friends." },
    { title: "Building a Character Development Plan", objective: "Create a practical weekly plan for improving one Islamic character trait at a time — a lifelong commitment." },
  ],

  // ── Journey 16: Quranic Tafseer ───────────────────────────────────────────
  tafseer: [
    { title: "What Is Tafseer?", objective: "Learn the definition, types, and importance of Quranic exegesis and the great scholars who dedicated their lives to it." },
    { title: "The Rules of Tafseer", objective: "Understand the Islamic methodology for interpreting the Quran — and the grave danger of interpretation without knowledge." },
    { title: "Tafseer of Surah Al-Fatiha", objective: "A verse-by-verse exploration of the opening chapter — the seven oft-repeated verses every Muslim recites." },
    { title: "Tafseer of Surah Al-Baqarah — Overview", objective: "Introduction to the longest surah: its themes, key passages, and central role in Islamic law." },
    { title: "Tafseer of Ayat al-Kursi (2:255)", objective: "The greatest verse in the Quran — its complete tafseer with the astonishing descriptions of Allah's majesty." },
    { title: "Tafseer of the Last Two Verses of Al-Baqarah", objective: "Learn the great merit and meaning of 2:285–286 — the verses the Prophet ﷺ commanded be memorised." },
    { title: "Tafseer of Surah Al-Kahf — The Four Stories", objective: "The companions of the cave, the man with two gardens, Musa and Khidr, Dhul Qarnayn — explained." },
    { title: "Tafseer of Surah Yasin", objective: "Why Yasin is 'the heart of the Quran' — its powerful address to the deniers and its message of resurrection." },
    { title: "Tafseer of Surah Al-Rahman", objective: "'Which of your Lord's favours will you deny?' — an exploration of this majestic surah's structure and message." },
    { title: "Tafseer of Surah Al-Waqiah", objective: "The surah of wealth and provision — its description of the three categories of people on the Day of Judgement." },
    { title: "Tafseer of Surah Al-Mulk", objective: "Protection from the punishment of the grave — the meaning behind each passage of this crucial surah." },
    { title: "Tafseer of Juz Amma — Part 1", objective: "Detailed tafseer of Surahs Al-Fajr, Al-Balad, Al-Shams, Al-Layl, and Al-Duha." },
    { title: "Tafseer of Juz Amma — Part 2", objective: "Detailed tafseer of Surahs Al-Inshirah, Al-Tin, Al-Alaq, Al-Qadr, and Al-Bayyinah." },
    { title: "Tafseer of Juz Amma — Part 3", objective: "Detailed tafseer of Surahs Al-Zilzal, Al-Adiyat, Al-Qari'ah, Al-Takathur, and Al-Asr." },
    { title: "Tafseer of Juz Amma — Part 4", objective: "Detailed tafseer of Surahs Al-Humazah, Al-Fil, Quraysh, Al-Ma'un, and Al-Kawthar." },
    { title: "Tafseer of Al-Kafiroon, Al-Nasr, Al-Masad", objective: "Understanding these powerful concluding surahs of Juz Amma and the historical context behind them." },
    { title: "Tafseer of Al-Ikhlas, Al-Falaq, Al-Nas", objective: "The three surahs the Prophet ﷺ recited every night — their complete tafseer and significance." },
    { title: "Themes of the Quran — A Thematic Study", objective: "Explore the recurring themes of the Quran: Tawheed, accountability, prophets, and the Hereafter." },
    { title: "The Great Tafseer Works", objective: "A guide to the great tafseer books (Ibn Kathir, Al-Baghawi, Al-Tabari) and how to study them." },
    { title: "How to Study Tafseer for Life", objective: "Build a lifelong tafseer study plan — weekly routines, recommended books, and how to go deeper." },
  ],

  // ── Journey 17: Islamic Ethics & Society ─────────────────────────────────
  ethics: [
    { title: "Islamic Ethics — An Introduction", objective: "Understand the foundations of Islamic ethical theory (akhlaq) and how it differs from secular ethics." },
    { title: "The Sources of Islamic Ethics", objective: "Learn how the Quran, Sunnah, and scholarly tradition define right and wrong beyond just rules." },
    { title: "Rights of the Self (Huqooq al-Nafs)", objective: "Learn the Islamic obligation to take care of your own physical, mental, and spiritual wellbeing." },
    { title: "Rights of the Family", objective: "A comprehensive look at the rights and duties within the family: spouses, children, parents, siblings." },
    { title: "Rights of the Neighbour", objective: "Go deeper into the extraordinary rights Islam grants to neighbours — up to 40 houses in each direction." },
    { title: "Rights of the Worker and Employer", objective: "Learn Islamic employment ethics: fair wages, honest work, and the rights of both employer and employee." },
    { title: "Rights of the Natural World", objective: "Understand the Islamic concept of environmental stewardship and the prohibition of wasteful destruction." },
    { title: "Islamic Media Ethics", objective: "Apply Islamic principles to reporting, sharing, verifying information, and responsible social media use." },
    { title: "The Ethics of Disagreement in Islam", objective: "Learn how scholars debate in Islam — with evidence, respect, and recognition of valid differences of opinion." },
    { title: "Standing for Justice in Islam", objective: "Discover what the Quran demands from believers in terms of standing up for truth even against themselves." },
    { title: "The Ethics of Wealth — Earning and Spending", objective: "Islam's complete ethical framework around how to earn, how to spend, and what to avoid." },
    { title: "Relationships Before Marriage — Islamic Limits", objective: "Understand the Islamic boundaries on interaction between men and women and the wisdom behind them." },
    { title: "Dawah — Calling to Islam With Wisdom", objective: "Learn the Islamic ethics of inviting others to the faith: with wisdom, beautiful preaching, and gentle debate." },
    { title: "The Muslim as a Citizen", objective: "Understand the Islamic duty to be a productive, just, and responsible citizen wherever you live." },
    { title: "Conflict Resolution in Islam", objective: "Learn the Islamic way to resolve disputes: through counsel, mediation, and Islamic arbitration." },
    { title: "Privacy and Dignity in Islam", objective: "Understand the Islamic prohibitions on spying, backbiting (gheebah), and violating others' privacy." },
    { title: "Backbiting, Slander, and the Tongue", objective: "Learn what gheebah and buhtan are, their grave sins, and the Islamic path to purifying your speech." },
    { title: "Islamic Ethics on Social Justice", objective: "How Islam addresses poverty, oppression, discrimination, and the duty of the privileged to help others." },
    { title: "Business Ethics and Commerce", objective: "Comprehensive Islamic ethics for trade: transparency, honesty, and avoiding forbidden transactions." },
    { title: "Living an Ethical Muslim Life", objective: "A practical framework for applying Islamic ethics to every role — parent, employee, citizen, believer." },
  ],

  // ── Journey 18: Spiritual Development ────────────────────────────────────
  spirituality: [
    { title: "The Journey of the Soul — An Overview", objective: "Understand the Islamic view of the soul (ruh), its origin, its purpose in this world, and its eternal destination." },
    { title: "The Levels of the Nafs", objective: "Learn about the three states of the self: the commanding soul, the blaming soul, and the tranquil soul." },
    { title: "What Is Ihsan?", objective: "The highest level of worship: 'worship Allah as if you see Him' — understanding and striving for ihsan." },
    { title: "Purifying the Heart (Tazkiyah al-Nafs)", objective: "The Islamic science of heart purification — its diseases, their cures, and the path to a sound heart." },
    { title: "The Diseases of the Heart", objective: "An in-depth study of pride, envy, rancour, and love of dunya as spiritual diseases with Quranic cures." },
    { title: "The Stations of the Spiritual Path", objective: "Introduction to the maqamat: tawbah, zuhd, sabr, shukr, tawakkul, and rida — stepping stones to Allah ﷻ." },
    { title: "Zuhd — Detachment from the Dunya", objective: "Learn what Islamic asceticism means (it is NOT monasticism) and how to live lightly without rejecting the world." },
    { title: "Connecting with Allah Through Du'a", objective: "How to transform dua from a ritual request into a genuine intimate conversation with Allah ﷻ." },
    { title: "Connecting with Allah Through the Quran", objective: "Making the Quran a source of guidance, healing, comfort, and closeness to Allah in your daily life." },
    { title: "The Heart in Prayer — Khushu' in Salah", objective: "How to achieve true humility and presence of heart in salah — the practical path to khushu'." },
    { title: "Spiritual Accountability — Muhasabah", objective: "The nightly practice of self-accounting recommended by Umar (RA) and its transforming effect." },
    { title: "Dealing with Doubts and Waswas", objective: "Learn the Islamic way to handle intrusive thoughts about aqeedah, prayer, and purity — the Shaytan's weapon." },
    { title: "Finding Peace in Trials", objective: "How the Quran teaches believers to process hardship: through sabr, shukr, and trust in Allah's wisdom." },
    { title: "Gratitude as a Spiritual Practice", objective: "Go beyond saying 'Alhamdulillah' — learn what it means to embody gratitude in your entire life." },
    { title: "The Love of Allah — Signs and Fruits", objective: "What does it mean to truly love Allah ﷻ? Learn the signs that you love Him and the fruits that come with it." },
    { title: "Fear and Hope — The Wings of Faith", objective: "The balanced approach to Allah's mercy (raja) and His punishment (khawf) that keeps a believer steady." },
    { title: "Death and the Afterlife as Motivation", objective: "How keeping death in mind (dhikr al-mawt) is not morbid but is the greatest spiritual motivator." },
    { title: "Spiritual Companionship", objective: "The Islamic tradition of learning spirituality from those who have walked the path before you." },
    { title: "The Concept of Tawakkul — A Deeper Study", objective: "A deeper exploration of trust in Allah — the misunderstandings and the correct practice of reliance." },
    { title: "The Spiritual Roadmap — Where Do You Go Next?", objective: "A complete review of the spiritual journey and a personal plan for continuing to grow in your relationship with Allah ﷻ." },
  ],

  // ── Journey 19: Zakat, Hajj & Finance ────────────────────────────────────
  finance_hajj: [
    { title: "The Obligation of Zakat — Who Must Pay", objective: "Learn who zakat is obligatory upon, the types of wealth it applies to, and the nisab threshold." },
    { title: "Calculating Your Zakat", objective: "A practical guide to calculating zakat on cash, gold, silver, business inventory, and livestock." },
    { title: "The Eight Recipients of Zakat", objective: "Learn the eight categories of people who can receive zakat as listed in Quran 9:60 and how to prioritise them." },
    { title: "Sadaqah — Voluntary Charity", objective: "Understand the different forms of voluntary charity, their immense rewards, and how to build a habit of giving." },
    { title: "The Wonders of Sadaqah Jariyah", objective: "Discover the ongoing charity (sadaqah jariyah) that continues to benefit a believer even after death." },
    { title: "Islamic Finance — Fundamentals", objective: "Understand the prohibition of riba (interest), gharar (uncertainty), and maysir (gambling) in Islamic economics." },
    { title: "Halal Investment Today", objective: "Survey the halal investment landscape: ethical funds, sukuk, REITs, and what to look for in halal portfolios." },
    { title: "The Introduction to Hajj", objective: "Learn the obligation of Hajj, who it is compulsory for, and the profound spiritual significance of the pilgrimage." },
    { title: "The History of the Ka'bah", objective: "Discover the story of the Ka'bah from Ibrahim (AS) to today and why it is the direction of Muslim prayer." },
    { title: "The Pillars of Hajj", objective: "Master the obligatory pillars of Hajj: Ihram, Tawaf, Sa'i, Wuquf at Arafah, and their order." },
    { title: "The Wajibat (Obligatory Acts) of Hajj", objective: "Learn the obligatory elements of Hajj and the penalty (fidyah) for missing them." },
    { title: "The Days of Hajj — Step by Step", objective: "A day-by-day walkthrough of Hajj from entering ihram to the farewell tawaf." },
    { title: "Hajj al-Qiran, Tamattu, and Ifrad", objective: "Learn the three ways to perform Hajj and which one is recommended by most scholars." },
    { title: "Umrah — The Lesser Pilgrimage", objective: "The four pillars of Umrah: ihram, tawaf, sa'i, and shaving/cutting hair — with complete details." },
    { title: "The Etiquette of Makkah and Madinah", objective: "Learn the specific duas, etiquette, and Sunnah practices in the two most sacred cities." },
    { title: "Visiting the Prophet's Masjid in Madinah", objective: "Learn about the masjid, the rawdah, and the etiquette of visiting the Prophet's ﷺ grave." },
    { title: "Spiritual Preparation for Hajj", objective: "How to prepare spiritually — tawbah, resolving debts and disputes, and setting the intention before travelling." },
    { title: "Maximising Hajj Spiritually", objective: "How to make every moment of Hajj a profound spiritual experience — practical tips from scholars." },
    { title: "After Hajj — The Returning Pilgrim", objective: "What changes after Hajj: the new beginning, the ibadah to maintain, and the status of the Hajji." },
    { title: "Comprehensive Zakat, Hajj & Finance Review", objective: "A complete consolidation of all lessons on financial worship, pilgrimage, and halal finance." },
  ],

  // ── Journey 20: Comprehensive Review ─────────────────────────────────────
  review: [
    { title: "Review — Quran and Its Sciences", objective: "Key revision questions and concepts from the Quran lessons covered in Journey 1." },
    { title: "Review — Daily Duas and Adhkar", objective: "Consolidate your knowledge of the supplications and remembrances from Journey 2." },
    { title: "Review — Islamic Manners and Character", objective: "Test your knowledge of the manners and character traits covered in Journeys 3 and 15." },
    { title: "Review — The Seerah of the Prophet ﷺ", objective: "Key events, dates, and lessons from the life of the Prophet ﷺ in Journey 4." },
    { title: "Review — Stories of the Prophets", objective: "Quiz yourself on the key events and lessons from the prophets covered in Journey 5." },
    { title: "Review — Islamic History", objective: "Major events, caliphs, empires, and contributions from the history covered in Journey 6." },
    { title: "Review — Arabic Language I & II", objective: "Test your Arabic vocabulary, grammar, and reading comprehension from Journeys 7 and 8." },
    { title: "Review — Islamic Law (Fiqh) I & II", objective: "Key rulings from purification, prayer, zakat, fasting, hajj, and Islamic finance." },
    { title: "Review — Prayer (Salah)", objective: "Test your knowledge of prayer conditions, pillars, invalidators, and types of prayer from Journey 11." },
    { title: "Review — Dhikr, Fasting, and Ramadan", objective: "Key review of remembrance, fasting rules, and the spiritual practices of Ramadan from Journey 12." },
    { title: "Review — Islamic Creed (Aqeedah)", objective: "The six pillars of iman, tawheed categories, shirk, and aqeedah concepts from Journey 13." },
    { title: "Review — Hadith Sciences", objective: "Hadith grading, isnad, major collections, and 40 Hadith concepts from Journey 14." },
    { title: "Review — Tafseer", objective: "Test your understanding of the Quranic tafseer from Journey 16." },
    { title: "Review — Islamic Ethics", objective: "Apply the ethical frameworks from Journey 17 to real-life scenarios." },
    { title: "Review — Spiritual Development", objective: "Test your knowledge of tazkiyah, the stages of the nafs, and spiritual practices from Journey 18." },
    { title: "Review — Zakat, Hajj, and Finance", objective: "Final comprehensive revision on financial worship and pilgrimage from Journey 19." },
    { title: "Comprehensive Test — Part 1", objective: "A broad knowledge test covering Journeys 1–10 with questions from all major topics." },
    { title: "Comprehensive Test — Part 2", objective: "A broad knowledge test covering Journeys 11–20 with questions from all major topics." },
    { title: "Putting It All Together — Living Islam", objective: "Reflect on how all 19 journeys connect into one complete, beautiful way of life." },
    { title: "The End of the Beginning — Your Journey Continues", objective: "A final reflection on how to continue learning, growing, and serving the Ummah all your life." },
  ],
};
