export interface LessonMeta {
  title: string;
  objective: string;
}

export const TOPIC_LESSONS: Record<string, LessonMeta[]> = {
  quran: [
    { title: "Introduction to the Quran", objective: "Discover what the Quran is, how it was revealed, and why it holds the highest place in a Muslim's life." },
    { title: "Structure of the Quran", objective: "Learn how the Quran is organised into surahs, ayaat, juz', and hizb — and what each term means." },
    { title: "The Key Surahs", objective: "Explore the most important and frequently recited surahs used in daily Muslim life and prayer." },
    { title: "The Heart of the Quran", objective: "Understand why Surah Ya-Sin is called the heart of the Quran and when it should be recited." },
    { title: "Surahs of Protection", objective: "Learn about Al-Mu'awwidhatayn (Al-Falaq and An-Nas), Ayat al-Kursi, and their protective power." },
    { title: "The Art of Tajweed", objective: "Discover the rules of Tajweed and why precise pronunciation is a command from Allah ﷻ." },
    { title: "Reading with Meaning", objective: "Move beyond recitation to understanding what you are reading — reflecting on the words of Allah ﷻ." },
    { title: "Hifz: Memorising the Quran", objective: "Learn about the immense blessing of memorising the Quran and proven techniques to begin." },
    { title: "Rewards of Recitation", objective: "Discover the immense spiritual rewards promised by the Prophet ﷺ for engaging with the Quran daily." },
    { title: "Etiquette with the Quran", objective: "Learn the proper Islamic etiquette for handling, reciting, and showing respect to the Quran." },
    { title: "The Quran in Daily Prayer", objective: "Understand which surahs and verses are recited in Salah and the wisdom behind their selection." },
    { title: "The Quran: A Way of Life", objective: "See how the Quran provides complete guidance for every aspect of a Muslim's life." },
  ],

  duas: [
    { title: "What Is Du'a?", objective: "Understand what supplication is, why the Prophet ﷺ called it the essence of worship, and when Allah answers." },
    { title: "Duas Before and After Eating", objective: "Master the taught supplications for beginning and ending a meal in the Sunnah way." },
    { title: "Duas for Purification", objective: "Learn the duas for entering and leaving the toilet, beginning wudu, and completing ghusl." },
    { title: "Duas During Prayer", objective: "Discover the supplications made at different points within the Salah itself." },
    { title: "Morning Adhkar", objective: "Learn the morning remembrances that protect, bless, and set the right intention for your day." },
    { title: "Evening Adhkar", objective: "Discover the evening remembrances that close the day in the remembrance of Allah ﷻ." },
    { title: "Duas for Sleeping and Waking", objective: "Learn the Prophet's ﷺ taught supplications before sleeping and upon waking each morning." },
    { title: "Duas When Entering and Leaving Home", objective: "Understand the protective Sunnah duas when leaving and returning to your home." },
    { title: "Duas for Travel", objective: "Master the supplications for safe, blessed travel by any means of transport." },
    { title: "Duas for the Masjid and Market", objective: "Learn specific duas for entering and leaving the masjid and navigating the marketplace." },
    { title: "Duas in Times of Hardship", objective: "Learn powerful duas for facing difficulties, grief, anxiety, and loss with faith." },
    { title: "Duas for Forgiveness", objective: "Master Sayyidul Istighfar and other comprehensive duas for seeking Allah's pardon." },
    { title: "Duas from the Prophets", objective: "Learn the heartfelt duas made by the Prophets in the Quran — and what we can take from them." },
    { title: "Duas for the Family", objective: "Discover supplications for spouse, children, parents, and those you love." },
    { title: "Duas for the Sick", objective: "Learn how to make dua for yourself and others when facing illness, citing ruqyah principles." },
    { title: "Duas for Special Occasions", objective: "Master duas for Ramadan, Laylat al-Qadr, Eid, marriage, and life's major moments." },
    { title: "Duas for Protection", objective: "Learn the comprehensive duas for protection from Shaytan, evil eye, and harm." },
    { title: "Duas for Knowledge and Guidance", objective: "Discover supplications for increasing knowledge, wisdom, and staying on the straight path." },
    { title: "Tahajjud and Night Duas", objective: "Learn the special supplications of the night prayer and when Allah descends to the lower heavens." },
    { title: "Living in Constant Remembrance", objective: "Learn how to make dhikr a natural, flowing part of every moment of your day." },
  ],

  manners: [
    { title: "The Importance of Good Character", objective: "Understand why the Prophet ﷺ said he was sent to perfect good character and what akhlaq really means." },
    { title: "Honesty and Trustworthiness", objective: "Learn about the quality of siddiq and why the Prophet ﷺ was called Al-Amin before prophethood." },
    { title: "Respect for Parents and Elders", objective: "Discover the extraordinary rank of parents in Islam and the exact duties owed to them." },
    { title: "The Islamic Greeting (Salaam)", objective: "Master the full Islamic greeting, its etiquette, and the rewards promised for spreading salaam." },
    { title: "Table Manners and Eating Etiquette", objective: "Learn every Sunnah practice around food, drink, and sharing meals with others." },
    { title: "Social Etiquette and Visiting", objective: "Understand Islamic manners for visiting others, hosting guests, and maintaining community ties." },
    { title: "Controlling Anger and Patience", objective: "Discover the Islamic strategies for managing anger — and why the Prophet ﷺ repeated 'Do not be angry' three times." },
    { title: "Generosity and Avoiding Waste", objective: "Learn the Islamic balance between generous giving and avoiding the sin of israf (extravagance)." },
  ],

  seerah: [
    { title: "Arabia Before Islam", objective: "Understand the social, political, and moral state of Arabia before the birth of the Prophet ﷺ." },
    { title: "The Birth and Early Life", objective: "Learn about the miraculous year of the Prophet's ﷺ birth and his orphaned, blessed childhood." },
    { title: "Youth and Character", objective: "Discover the remarkable character of Al-Amin in his youth — before the first revelation arrived." },
    { title: "Marriage to Khadijah (RA)", objective: "Learn about the Prophet's ﷺ blessed marriage, Khadijah's role, and why she was the greatest of women." },
    { title: "The First Revelation", objective: "Experience the momentous night in Cave Hira when Jibreel (AS) first appeared to the Prophet ﷺ." },
    { title: "The Early Muslims and Persecution", objective: "Discover who the first Muslims were and how they endured brutal persecution with steadfast faith." },
    { title: "Migration to Abyssinia", objective: "Understand why the Prophet ﷺ sent early Muslims to Christian Abyssinia and what this teaches about seeking justice." },
    { title: "The Year of Grief and Isra wal Mi'raj", objective: "Learn about the deaths of Khadijah (RA) and Abu Talib, and the miraculous Night Journey that followed." },
    { title: "The Hijra to Madinah", objective: "Follow the Prophet's ﷺ migration in detail — the planning, the journey, and the arrival." },
    { title: "Building the Islamic State", objective: "How the Prophet ﷺ built the first Muslim community: the masjid, the brotherhood, and the constitution." },
    { title: "Battles of Badr and Uhud", objective: "Learn from the first major battles in Islamic history — triumph at Badr, lessons at Uhud." },
    { title: "The Conquest of Makkah", objective: "Follow the peaceful liberation of Makkah and witness the Prophet's ﷺ extraordinary mercy to his enemies." },
    { title: "The Farewell Sermon", objective: "Study the Prophet's ﷺ final sermon — the most important speech in Islamic history." },
    { title: "The Companions (Sahabah)", objective: "Meet the key companions who sacrificed everything for Islam and shaped the early Ummah." },
    { title: "The Legacy of the Prophet ﷺ", objective: "Reflect on what the Prophet ﷺ left for all of humanity — until the Day of Judgment." },
  ],

  prophets: [
    { title: "Believing in the Prophets", objective: "Understand the Islamic belief (aqeedah) regarding prophethood — who the prophets were and their essential qualities." },
    { title: "Adam and Hawa (AS)", objective: "Learn about the creation of the first humans, life in Jannah, and the beginning of humanity on earth." },
    { title: "Nuh (AS) and the Ark", objective: "Follow the remarkable story of Nuh (AS) — 950 years of calling his people and building the great ark." },
    { title: "Ibrahim (AS): Friend of Allah", objective: "Learn about the father of monotheism, his extraordinary tests, and why Allah took him as a close friend." },
    { title: "Musa (AS) and the Pharaoh", objective: "Follow the epic story of Musa (AS) — from the Nile to Mount Sinai and the parting of the sea." },
    { title: "Dawud and Sulayman (AS)", objective: "Discover the prophets who were also kings, gifted with extraordinary blessings and divine abilities." },
    { title: "Yunus and Ayyub (AS)", objective: "Learn from the stories of patience, prayer, and redemption — inside a whale and through years of suffering." },
    { title: "Isa ibn Maryam (AS)", objective: "Understand the Islamic belief about Isa (AS), his miraculous birth, and his role before the Day of Judgment." },
    { title: "The Seal of the Prophets ﷺ", objective: "Understand why Muhammad ﷺ is the final prophet and what this means for all of humanity." },
    { title: "Lessons from the Prophets", objective: "Draw timeless practical lessons from the lives of all the prophets for your life today." },
  ],

  history: [
    { title: "The Rightly Guided Caliphs", objective: "Introduction to the four caliphs who followed the Prophet ﷺ and why they are called 'Rightly Guided'." },
    { title: "Abu Bakr al-Siddiq (RA)", objective: "Learn how the first caliph held the Ummah together in the most critical moments after the Prophet's ﷺ death." },
    { title: "Umar ibn al-Khattab (RA)", objective: "Discover how the second caliph built the Islamic state into a world power through justice and wisdom." },
    { title: "Uthman and Ali (RA)", objective: "Learn about the third and fourth caliphs, their achievements, and the trials that tested the Ummah." },
    { title: "The Umayyad Caliphate", objective: "Understand Islam's first hereditary dynasty and the remarkable expansion to Spain and Central Asia." },
    { title: "The Abbasid Golden Age", objective: "Explore the height of Islamic civilisation when Baghdad led the world in art, science, and scholarship." },
    { title: "The House of Wisdom", objective: "Discover Bayt al-Hikmah and the Islamic Golden Age contributions that shaped world knowledge." },
    { title: "Al-Andalus: Islam in Spain", objective: "Learn about 800 years of flourishing Muslim civilisation on European soil." },
    { title: "The Crusades and Salahuddin", objective: "Understand the Crusades and the Muslim response under the great Salahuddin al-Ayyubi." },
    { title: "The Mongol Invasion", objective: "Learn how the Mongols devastated Baghdad and how Islam survived and eventually transformed the Mongols." },
    { title: "The Ottoman Empire", objective: "Explore six centuries of Islamic governance that spanned three continents." },
    { title: "Muslim Scholars and Scientists", objective: "Meet the giants of Islamic learning whose discoveries changed the course of human civilisation." },
    { title: "The Fall of the Ottoman Empire", objective: "Understand the events that ended the last Islamic caliphate and their impact on the Muslim world." },
    { title: "Islam in the Modern World", objective: "Survey the Muslim world from colonialism to the present day and the challenges and opportunities ahead." },
  ],

  fiqh: [
    { title: "Introduction to Islamic Law", objective: "Understand what fiqh is, its four primary sources, and why studying it is an obligation upon every Muslim." },
    { title: "The Five Pillars of Islam", objective: "A deep dive into the five foundational pillars that structure every Muslim's life and worship." },
    { title: "Purification (Taharah)", objective: "Master wudu, ghusl, tayammum, and the types of impurity that must be removed before worship." },
    { title: "Salah — Foundations", objective: "Learn the conditions, pillars, and obligatory elements that make each prayer valid before Allah ﷻ." },
    { title: "Salah — Times and Types", objective: "Understand the five daily prayers, Friday (Jumuah), Eid, and the Sunnah and voluntary prayers." },
    { title: "Zakat: Obligatory Charity", objective: "Learn the nisab, rate, categories of wealth, and who is eligible to receive zakat." },
    { title: "Fasting in Ramadan (Sawm)", objective: "Understand the rules, exemptions, things that break the fast, and the spiritual purpose of fasting." },
    { title: "Hajj and Umrah", objective: "Learn the pillars of Hajj, the rites of Umrah, and the conditions that make Hajj obligatory." },
    { title: "Halal and Haram Food", objective: "Master Islamic dietary law: what is permitted, what is forbidden, and how to verify food is halal." },
    { title: "Islamic Finance: Avoiding Riba", objective: "Understand why riba (interest/usury) is forbidden and what halal financial alternatives exist." },
    { title: "Family Law: Marriage (Nikah)", objective: "Learn the requirements for a valid nikah, the rights of spouses, and the wisdom in Islamic marriage law." },
    { title: "Family Law: Divorce and After", objective: "Understand talaq, khul', the iddah waiting period, and children's rights in Islamic family law." },
    { title: "The Four Madhabs", objective: "Understand the four Sunni schools of jurisprudence, their founders, and how to follow one correctly." },
    { title: "Fiqh of Worship in Detail", objective: "Deeper rulings on prayer, fasting, zakat, and hajj — the fine details every Muslim should know." },
    { title: "Business Ethics in Islam", objective: "Learn the Islamic principles governing trade, contracts, forbidden transactions, and marketplace conduct." },
    { title: "Rights and Responsibilities", objective: "Understand the rights of Allah, yourself, your family, your community, and all of creation." },
    { title: "Contemporary Fiqh Issues", objective: "Learn how Islamic scholars address modern questions: halal investing, organ donation, social media conduct." },
    { title: "Revision: Essential Islamic Rulings", objective: "A comprehensive review of the most important rulings from all fiqh topics — consolidating your knowledge." },
  ],

  arabic: [
    { title: "The Arabic Alphabet — Part 1", objective: "Begin your Arabic journey with the first seven letters, their shapes, and the sounds they make." },
    { title: "The Arabic Alphabet — Part 2", objective: "Continue with the next group of Arabic letters, building your recognition and pronunciation." },
    { title: "The Arabic Alphabet — Part 3", objective: "Learn the third set of Arabic letters — you are more than halfway through the alphabet." },
    { title: "The Arabic Alphabet — Part 4", objective: "Complete the Arabic alphabet with the final letters, giving you the full 28-letter foundation." },
    { title: "Connecting Arabic Letters", objective: "Understand how Arabic letters connect in words and how most letters change form in different positions." },
    { title: "Short Vowels (Harakat)", objective: "Learn the three short vowels — fatha (a), kasra (i), damma (u) — and how they change word meanings." },
    { title: "The Definite Article (Al)", objective: "Master 'Al' (the), the sun and moon letter categories, and how it attaches to Arabic nouns." },
    { title: "Essential Islamic Vocabulary", objective: "Learn the most important Islamic terms in Arabic — the words you will encounter in worship every day." },
    { title: "Pronouns in Arabic", objective: "Learn personal pronouns — I, you, he, she, we, they — and how they work in Arabic sentences." },
    { title: "Greetings and Daily Phrases", objective: "Master practical Islamic greetings and the everyday phrases a Muslim uses in conversation." },
    { title: "Names of Allah (Asma ul Husna)", objective: "Learn the 99 beautiful names of Allah ﷻ, their meanings, and how to incorporate them into dhikr." },
    { title: "The Arabic Root System", objective: "Unlock the secret of Arabic: understand the three-letter root system that gives Arabic its unique structure." },
    { title: "Core Quranic Vocabulary", objective: "Learn the 100 most frequently used words in the Quran — understanding them unlocks a huge portion of the text." },
    { title: "Asking Questions in Arabic", objective: "Master the question words: man (who), ma (what), mata (when), ayna (where), kayfa (how), limadha (why)." },
    { title: "Quranic Vocabulary: Al-Fatiha", objective: "Go through every word of Surah Al-Fatiha in Arabic — the surah you recite in every prayer." },
    { title: "Quranic Vocabulary: Short Surahs", objective: "Study key vocabulary from the Juz' Amma (30th juz') — the surahs most commonly memorised and recited." },
    { title: "Arabic in Prayer (Salah)", objective: "Understand the meaning of every Arabic phrase and dua recited during the five daily prayers." },
    { title: "Arabic Numbers", objective: "Learn Arabic numbers from 1-100 and how to express quantities in everyday Islamic contexts." },
    { title: "Vocabulary of the Prophets' Stories", objective: "Key Arabic words from the Quranic stories of the prophets — expanding your Quranic comprehension." },
    { title: "Simple Arabic Sentences", objective: "Combine what you have learned to form basic Arabic sentences about Islamic topics." },
    { title: "Understanding Hadith Arabic", objective: "Learn the common Arabic patterns and vocabulary that appear most frequently in hadith collections." },
    { title: "Arabic Verbs — Introduction", objective: "Understand the past, present, and command verb forms and how they work in Arabic." },
    { title: "Reading Islamic Arabic Phrases", objective: "Practice reading short Islamic phrases and Quranic extracts, building your fluency." },
    { title: "Arabic Revision and Consolidation", objective: "A comprehensive review of everything learned — vocabulary, grammar, Quranic terms, and daily phrases." },
  ],

  salah: [
    { title: "The Importance of Salah", objective: "Understand why Salah is the pillar of the deen and the first thing we will be asked about on Yawm al-Qiyamah." },
    { title: "The Conditions of Prayer", objective: "Learn the prerequisites for a valid prayer: purity, awrah, Qibla, intention, and correct prayer time." },
    { title: "The Pillars (Arkaan) of Salah", objective: "Master the obligatory components that, if missed, completely invalidate your prayer." },
    { title: "The Wajibat of Salah", objective: "Understand the obligatory elements of prayer that require a prostration of forgetfulness (sujood as-sahw) if missed." },
    { title: "Prayer Times and Their Wisdom", objective: "Learn the five daily prayer windows, the best time to pray within each, and the wisdom behind their timing." },
    { title: "The Movements of Salah", objective: "Follow each position from Qiyam to Salam with their recitations, reflecting on what each position means." },
    { title: "What Invalidates Prayer", objective: "Learn the actions that break Salah — speaking, laughing, intentional movement, breaking wudu — and how to avoid them." },
    { title: "Sunnah and Voluntary Prayers", objective: "Discover the rawatib (regular Sunnah prayers), Tahajjud, Duha, and how extra prayers build closeness to Allah ﷻ." },
  ],

  dhikr: [
    { title: "Why Dhikr Nourishes the Soul", objective: "Understand why the Quran says 'Verily in the remembrance of Allah do hearts find rest' (13:28) — the science of the soul." },
    { title: "Morning Adhkar (Sabah)", objective: "Learn the complete morning routine of remembrance with their specific wording, frequency, and incredible rewards." },
    { title: "Evening Adhkar (Masa)", objective: "Master the evening remembrances that seal your day in Allah's ﷻ protection and mercy." },
    { title: "Dhikr After Every Salah", objective: "Learn the exact post-prayer dhikr taught by the Prophet ﷺ — SubhanAllah, Alhamdulillah, Allahu Akbar — and their count." },
    { title: "The Power of Istighfar", objective: "Discover why seeking forgiveness is one of the most powerful acts of worship and when it should be said." },
    { title: "Dhikr Throughout the Day", objective: "Learn short yet powerful phrases for every daily activity: eating, dressing, travelling, and more." },
    { title: "The 99 Beautiful Names of Allah", objective: "Learn Allah's ﷻ Asma ul-Husna — their meanings and how calling upon them transforms your dhikr and connection." },
  ],

  fasting: [
    { title: "The Obligation and Virtue of Fasting", objective: "Understand when fasting Ramadan became obligatory, who must fast, and the extraordinary rewards promised in authentic hadith." },
    { title: "The Pillars and Conditions of Sawm", objective: "Learn what makes a fast valid: the intention (niyyah), abstaining from all nullifiers, and the valid fast period." },
    { title: "What Breaks the Fast", objective: "Master the things that nullify the fast — eating, drinking, intentional vomiting, marital relations — and the kaffarah for deliberate violations." },
    { title: "The Sunnah of Ramadan", objective: "Discover the Prophet's ﷺ complete Ramadan routine: suhoor, iftar dua, tarawih, i'tikaf, and extra worship." },
    { title: "Laylat al-Qadr and the Last Ten Nights", objective: "Learn why the Night of Power (better than 1,000 months) must be sought in the last ten nights and exactly how to make the most of it." },
  ],

  aqeedah: [
    { title: "The Six Pillars of Iman", objective: "Understand the six foundational beliefs every Muslim must hold — and what denying any one of them means for one's faith." },
    { title: "Tawheed: The Oneness of Allah", objective: "Learn the three categories of Tawheed — Rububiyyah, Uluhiyyah, and Asma wa Sifat — and why Tawheed is the most important principle in Islam." },
    { title: "Belief in the Angels", objective: "Discover the nature, roles, and names of the angels — including Jibreel, Mikail, Israfeel, and Munkar and Nakeer." },
    { title: "Belief in the Divine Books", objective: "Learn about the scriptures Allah ﷻ revealed — the Tawrah, Injeel, Zabur, and the Quran — and why the Quran supersedes all." },
    { title: "Belief in All the Prophets", objective: "Understand the Aqeedah obligation to believe in all 124,000 prophets, their essential qualities, and the 25 mentioned in the Quran." },
    { title: "Belief in the Day of Judgement", objective: "Learn the major and minor signs of the Hour, the stages of the Hereafter, and what happens between death and resurrection." },
    { title: "Belief in Qadr (Divine Decree)", objective: "Understand the four levels of Qadr — knowledge, writing, will, and creation — and how believing in Qadr brings peace to a believer's heart." },
    { title: "Shirk: The Greatest Sin", objective: "Learn what constitutes shirk (associating partners with Allah), why it is the one unforgivable sin (if died upon), and how to protect your Tawheed." },
  ],

  hadith_sci: [
    { title: "What Is Hadith and Why It Matters", objective: "Understand what hadith is, how it differs from Quran, and why the Prophet's ﷺ sunnah is the second source of Islamic law." },
    { title: "The Isnad — Chain of Narrators", objective: "Learn what the chain of transmission (isnad) is and why Ibn al-Mubarak said 'The isnad is part of the religion.'" },
    { title: "Categories: Sahih, Hasan, Da'if", objective: "Understand the grading system for hadith — authentic, good, weak — and how scholars determined reliability." },
    { title: "The Six Major Hadith Collections", objective: "Learn about the Kutub al-Sittah (Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasa'i, Ibn Majah) and what makes Bukhari and Muslim the most reliable." },
    { title: "How Scholars Verified Narrators", objective: "Discover the science of Ilm al-Rijal (narrator criticism) — how scholars investigated the memory, character, and connections of thousands of narrators." },
    { title: "How to Cite and Use Hadith", objective: "Learn the proper format for citing hadith with collection name and number, and how to use them correctly in Islamic discourse." },
  ],

  character: [
    { title: "Why Character Is the Core of Islam", objective: "Understand the Prophet's ﷺ statement 'I was sent to perfect good character' and what this tells us about the purpose of Islam." },
    { title: "Truthfulness (Sidq) and Its Rewards", objective: "Learn why truthfulness leads to righteousness and to Paradise, and how the Prophet ﷺ embodied Sidq before and after prophethood." },
    { title: "Patience (Sabr) and Its Three Types", objective: "Discover the three types of Sabr — patience in obedience, patience in avoiding sin, and patience in trials — and their enormous rewards." },
    { title: "Generosity (Karam) in the Sunnah", objective: "Learn how the Prophet ﷺ was 'more generous than the flowing wind' and how generosity protects the heart from the love of dunya." },
    { title: "Humility (Tawadu) Over Arrogance", objective: "Understand why Islam considers arrogance one of the most destructive traits and how humility elevates a person in the sight of Allah ﷻ." },
    { title: "Controlling Anger in Islam", objective: "Learn the famous advice 'Do not be angry' (repeated three times), the Islamic tools for managing anger, and what strength really means." },
  ],
};
